<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+a', function assets() {
         window.location.href = BASE_URL + '/administrator/Tiktok_products/add';
         return false;
      });

      $('*').bind('keydown', 'Ctrl+f', function assets() {
         $('#sbtn').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#reset').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+b', function assets() {

         $('#reset').trigger('click');
         return false;
      });
   }

   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_products') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tiktok_products') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tiktok_products_add', function () { ?>
                           <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new"
                              title="<?= cclang('add_new_button', [cclang('tiktok_products')]); ?>  (Ctrl+a)"
                              href="<?= site_url('administrator/tiktok_products/add'); ?>"><i
                                 class="fa fa-plus-square-o"></i>
                              <?= cclang('add_new_button', [cclang('tiktok_products')]); ?></a>
                           <a class="btn btn-flat btn-success" id="btn_sync" title="Sinkronkan Produk dari TikTok"
                              href="<?= site_url('administrator/tiktok_products/sync'); ?>"><i class="fa fa-refresh"></i>
                              Sinkronkan Produk</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_products_export', function () { ?>
                           <a class="btn btn-flat btn-success"
                              title="<?= cclang('export'); ?> <?= cclang('tiktok_products') ?>']); ?>"
                              href="<?= site_url('administrator/tiktok_products/export'); ?>"><i
                                 class="fa fa-file-excel-o"></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_products_export', function () { ?>
                           <a class="btn btn-flat btn-success"
                              title="<?= cclang('export'); ?> pdf <?= cclang('tiktok_products') ?>']); ?>"
                              href="<?= site_url('administrator/tiktok_products/export_pdf'); ?>"><i
                                 class="fa fa-file-pdf-o"></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_products') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tiktok_products')]); ?> <i
                           class="label bg-yellow"><?= $tiktok_products_counts; ?> <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tiktok_products" id="form_tiktok_products"
                     action="<?= base_url('administrator/tiktok_products/index'); ?>">


                     <div class="table-responsive">
                        <table class="table table-bordered table-striped dataTable">
                            <thead>
                               <tr>
                                  <th style="width: 40px; text-align: center;">
                                     <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="Pilih Semua">
                                  </th>
                                  <th style="width: 70px; text-align: center;">Gambar</th>
                                  <th style="width: 25%;">Nama Produk</th>
                                  <th style="width: 17%;">ID Produk</th>
                                  <th style="width: 14%;">Toko</th>
                                  <th style="width: 9%; text-align: center;">Stok</th>
                                  <th style="width: 13%;">Harga</th>
                                  <th style="width: 10%; text-align: center;">Status</th>
                                  <th style="width: 12%; min-width: 140px; text-align: center;">Aksi</th>
                               </tr>
                            </thead>
                           <tbody id="tbody_tiktok_products">
                              <?php foreach ($tiktok_productss as $tiktok_products): ?>
                                 <tr>
                                     <td style="text-align: center;">
                                        <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tiktok_products->id; ?>">
                                     </td>
                                     <td style="text-align: center;">
                                        <?php if (!empty($tiktok_products->main_image)): ?>
                                           <?php if (strpos($tiktok_products->main_image, 'http://') === 0 || strpos($tiktok_products->main_image, 'https://') === 0): ?>
                                              <a class="fancybox" rel="group" href="<?= $tiktok_products->main_image; ?>">
                                                 <img src="<?= $tiktok_products->main_image; ?>" style="width: 45px; height: 45px; object-fit: cover; border-radius: 4px;" alt="image">
                                              </a>
                                           <?php elseif (is_image($tiktok_products->main_image)): ?>
                                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tiktok_products/' . $tiktok_products->main_image; ?>">
                                                 <img src="<?= BASE_URL . 'uploads/tiktok_products/' . $tiktok_products->main_image; ?>" style="width: 45px; height: 45px; object-fit: cover; border-radius: 4px;" alt="image">
                                              </a>
                                           <?php else: ?>
                                              <span class="text-muted">-</span>
                                           <?php endif; ?>
                                        <?php else: ?>
                                           <span class="text-muted">-</span>
                                        <?php endif; ?>
                                     </td>
                                     <td><?= _ent($tiktok_products->title); ?></td>
                                     <td><?= _ent($tiktok_products->product_id); ?></td>
                                     <td>
                                        <?php if ($tiktok_products->tiktok_shop_id) {
                                           echo anchor('administrator/tiktok_shops/view/' . $tiktok_products->tiktok_shop_id . '?popup=show', $tiktok_products->tiktok_shops_shop_name, ['class' => 'popup-view']);
                                        } ?>
                                     </td>
                                     <td style="text-align: center;"><?= _ent($tiktok_products->total_stock); ?></td>
                                     <td>Rp <?= number_format($tiktok_products->price, 0, ',', '.'); ?></td>
                                     <td style="text-align: center;">
                                        <?php
                                        $status = strtoupper($tiktok_products->status);
                                        $badge_class = 'label-default';
                                        if ($status == 'LIVE' || $status == 'ACTIVATE') {
                                           $badge_class = 'label-success';
                                        } elseif ($status == 'DRAFT') {
                                           $badge_class = 'label-info';
                                        } elseif ($status == 'FAILED' || $status == 'PLATFORM_DEACTIVATED') {
                                           $badge_class = 'label-danger';
                                        } elseif ($status == 'SELLER_DEACTIVATED' || $status == 'FREEZE') {
                                           $badge_class = 'label-warning';
                                        }
                                        ?>
                                        <span class="label <?= $badge_class; ?>"><?= _ent($tiktok_products->status); ?></span>
                                     </td>
                                     <td style="text-align: center;">
                                        <?php is_allowed('tiktok_products_view', function () use ($tiktok_products) { ?>
                                           <a href="<?= site_url('administrator/tiktok_products/single_pdf/' . $tiktok_products->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?></a>
                                           <a href="<?= site_url('administrator/tiktok_products/view/' . $tiktok_products->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?></a>
                                        <?php }) ?>
                                        <?php is_allowed('tiktok_products_update', function () use ($tiktok_products) { ?>
                                           <a href="<?= site_url('administrator/tiktok_products/edit/' . $tiktok_products->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                                        <?php }) ?>
                                        <?php is_allowed('tiktok_products_delete', function () use ($tiktok_products) { ?>
                                           <a href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_products/delete/' . $tiktok_products->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                                        <?php }) ?>
                                     </td>
                                 </tr>
                              <?php endforeach; ?>
                              <?php if ($tiktok_products_counts == 0): ?>
                                 <tr>
                                    <td colspan="100">
                                        Data Produk TikTok belum tersedia
                                    </td>
                                 </tr>
                              <?php endif; ?>
                           </tbody>
                        </table>
                     </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 ">
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk"
                           placeholder="Site Email">
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply"
                           title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  ">
                        <input type="text" class="form-control" name="q" id="filter"
                           placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 ">
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field">
                           <option value=""><?= cclang('all'); ?></option>
                           <option <?= $this->input->get('f') == 'tiktok_shop_id' ? 'selected' : ''; ?>
                              value="tiktok_shop_id">Tiktok Shop Id</option>
                           <option <?= $this->input->get('f') == 'product_id' ? 'selected' : ''; ?> value="product_id">
                              Product Id</option>
                           <option <?= $this->input->get('f') == 'title' ? 'selected' : ''; ?> value="title">Title</option>
                           <option <?= $this->input->get('f') == 'main_image' ? 'selected' : ''; ?> value="main_image">Main
                              Image</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' : ''; ?> value="status">Status
                           </option>
                           <option <?= $this->input->get('f') == 'seller_sku' ? 'selected' : ''; ?> value="seller_sku">
                              Seller Sku</option>
                           <option <?= $this->input->get('f') == 'price' ? 'selected' : ''; ?> value="price">Price</option>
                           <option <?= $this->input->get('f') == 'total_stock' ? 'selected' : ''; ?> value="total_stock">
                              Total Stock</option>
                        </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply"
                           title="<?= cclang('filter_search'); ?>">
                           Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply"
                           href="<?= base_url('administrator/tiktok_products'); ?>"
                           title="<?= cclang('reset_filter'); ?>">
                           <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
   $(document).ready(function () {

      $('.remove-data').click(function () {

         var url = $(this).attr('data-href');

         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
         },
            function (isConfirm) {
               if (isConfirm) {
                  document.location.href = url;
               }
            });

         return false;
      });


      $('#apply').click(function () {

         var bulk = $('#bulk');
         var serialize_bulk = $('#form_tiktok_products').serialize();

         if (bulk.val() == 'delete') {
            swal({
               title: "<?= cclang('are_you_sure'); ?>",
               text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
               type: "warning",
               showCancelButton: true,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
               cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
               closeOnConfirm: true,
               closeOnCancel: true
            },
               function (isConfirm) {
                  if (isConfirm) {
                     document.location.href = BASE_URL + '/administrator/tiktok_products/delete?' + serialize_bulk;
                  }
               });

            return false;

         } else if (bulk.val() == '') {
            swal({
               title: "Upss",
               text: "<?= cclang('please_choose_bulk_action_first'); ?>",
               type: "warning",
               showCancelButton: false,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Okay!",
               closeOnConfirm: true,
               closeOnCancel: true
            });

            return false;
         }

         return false;

      });/*end appliy click*/


      //check all
      var checkAll = $('#check_all');
      var checkboxes = $('input.check');

      checkAll.on('ifChecked ifUnchecked', function (event) {
         if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
         } else {
            checkboxes.iCheck('uncheck');
         }
      });

      checkboxes.on('ifChanged', function (event) {
         if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
         } else {
            checkAll.removeProp('checked');
         }
         checkAll.iCheck('update');
      });

   }); /*end doc ready*/
</script>