<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Order TikTok      <small><?= cclang('detail', ['Order TikTok']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tiktok_orders'); ?>">Order TikTok</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Order TikTok</h3>
                     <h5 class="widget-user-desc">Detail Order TikTok</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_orders" id="form_tiktok_orders" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tiktok Shop Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->tiktok_shops_shop_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Status </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_status); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payment Method Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->payment_method_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Buyer Message </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->buyer_message); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cancel Reason </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->cancel_reason); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Recipient Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->recipient_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Recipient Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->recipient_phone); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Recipient Address </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->recipient_address); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Provider </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->shipping_provider); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Type </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->shipping_type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Delivery Option </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->delivery_option_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tracking Number </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->tracking_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Package Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->package_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Total Amount </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->total_amount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Fee </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->shipping_fee, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Seller Discount </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->seller_discount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tiktok Discount </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->tiktok_discount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Created Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_created_time); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Paid Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_paid_time); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="content" class="col-sm-2 control-label">Produk Dipesan </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr>
                                        <th width="60" class="text-center">Foto</th>
                                        <th>Nama Produk / Varian</th>
                                        <th width="120">Harga Satuan</th>
                                        <th width="70" class="text-center">Qty</th>
                                        <th width="130">Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($order_items)): ?>
                                        <?php foreach ($order_items as $item): ?>
                                            <tr>
                                                <td class="text-center" style="vertical-align: middle;">
                                                    <?php if (!empty($item->sku_image)): ?>
                                                        <img src="<?= $item->sku_image; ?>" style="width: 44px; height: 44px; object-fit: cover; border-radius: 4px; border: 1px solid #ddd;" alt="item">
                                                    <?php else: ?>
                                                        <span class="text-muted">-</span>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="vertical-align: middle;">
                                                    <div><?= _ent($item->product_name); ?></div>
                                                    <?php if (!empty($item->sku_name) && $item->sku_name != 'Default'): ?>
                                                        <small class="text-muted">Varian: <?= _ent($item->sku_name); ?></small>
                                                    <?php endif; ?>
                                                    <?php if (!empty($item->seller_sku)): ?>
                                                        <br><small class="text-muted">SKU: <?= _ent($item->seller_sku); ?></small>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="vertical-align: middle;">Rp <?= number_format($item->item_price, 0, ',', '.'); ?></td>
                                                <td class="text-center" style="vertical-align: middle;"><?= $item->quantity; ?></td>
                                                <td style="vertical-align: middle;">Rp <?= number_format($item->item_price * $item->quantity, 0, ',', '.'); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <tr>
                                            <td colspan="5" class="text-center text-muted">Tidak ada rincian produk.</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php if ($tiktok_orders->order_status == 'AWAITING_SHIPMENT'): ?>
                           <a class="btn btn-flat btn-default btn_action" title="Atur Pengiriman (Drop-off ke gerai)" href="<?= site_url('administrator/tiktok_orders/ship/'.$tiktok_orders->id); ?>"><i class="fa fa-truck" ></i> Atur Pengiriman</a>
                        <?php elseif (in_array($tiktok_orders->order_status, ['AWAITING_COLLECTION', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED'])): ?>
                           <a class="btn btn-flat btn-default btn_action" target="_blank" title="Cetak Label Resi (AWB PDF)" href="<?= site_url('administrator/tiktok_orders/print_label/'.$tiktok_orders->id); ?>"><i class="fa fa-barcode" ></i> Cetak Label Resi</a>
                            <a class="btn btn-flat btn-default btn_action" target="_blank" title="Cetak Daftar Pengemasan (Packing List PDF)" href="<?= site_url('administrator/tiktok_orders/print_packing_slip/' . $tiktok_orders->id); ?>"><i class="fa fa-archive" ></i> Cetak Daftar Pengemasan</a>
                         <?php endif; ?>
                         <a class="btn btn-flat btn-default btn_action" target="_blank" title="Cetak Daftar Pengambilan Barang (Pick List)" href="<?= site_url('administrator/tiktok_orders/print_pick_list/' . $tiktok_orders->id); ?>"><i class="fa fa-clipboard" ></i> Cetak Pengambilan Barang</a>
                        <?php if ($tiktok_orders->order_status != 'CANCELLED'): ?>
                         <a class="btn btn-flat btn-default btn_action cancel-data" href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_orders/cancel/' . $tiktok_orders->id); ?>" title="Batalkan Pesanan"><i class="fa fa-ban" ></i> Batalkan Pesanan</a>
                         <?php endif; ?>
                         <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tiktok_orders/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tiktok Orders']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).on('click', '.cancel-data', function(){
  var url = $(this).attr('data-href');
  swal({
      title: 'Batalkan Pesanan?',
      text: 'Pesanan ini akan dibatalkan di TikTok Shop dan Vendio. Apakah Anda yakin?',
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#DD6B55',
      confirmButtonText: 'Ya, Batalkan!',
      cancelButtonText: 'Batal',
      closeOnConfirm: true,
      closeOnCancel: true
    },
    function(isConfirm){
      if (isConfirm) {
        document.location.href = url;
      }
    });
  return false;
});
</script>
