<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pesanan Penjualan      <small><?= cclang('detail', ['Pesanan Penjualan']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tiktok_orders'); ?>">Pesanan Penjualan</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pesanan Penjualan</h3>
                     <h5 class="widget-user-desc">Detail Pesanan Penjualan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_orders" id="form_tiktok_orders" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tiktok Shop Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->tiktok_shops_shop_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Pesanan </label>

                        <div class="col-sm-8">
                           <?php 
                           switch ($tiktok_orders->order_status) {
                              case "UNPAID":
                                 echo '<span class="label label-info">Belum Bayar</span>';
                                 break;
                              case "ON_HOLD":
                                 echo '<span class="label label-warning">Ditahan</span>';
                                 break;
                              case "AWAITING_SHIPMENT":
                                 echo '<span class="label label-warning">Perlu Dikirim</span>';
                                 break;
                              case "AWAITING_COLLECTION":
                                 echo '<span class="label label-info">Menunggu Kurir</span>';
                                 break;
                               case "PARTIALLY_SHIPPING":
                                  echo '<span class="label label-info">Sebagian Dikirim</span>';
                                  break;
                              case "IN_TRANSIT":
                                 echo '<span class="label label-info">Sedang Dikirim</span>';
                                 break;
                              case "DELIVERED":
                                 echo '<span class="label label-primary">Terkirim</span>';
                                 break;
                              case "COMPLETED":
                                 echo '<span class="label label-success">Selesai</span>';
                                 break;
                              case "CANCELLED":
                                 echo '<span class="label label-danger">Dibatalkan</span>';
                                 break;
                              default:
                                 echo '<span class="label label-info">' . _ent($tiktok_orders->order_status) . '</span>';
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payment Method Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->payment_method_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Buyer Message </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->buyer_message); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cancel Reason </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->cancel_reason); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Recipient Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->recipient_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Recipient Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->recipient_phone); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Recipient Address </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->recipient_address); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Provider </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->shipping_provider); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Type </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->shipping_type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Delivery Option </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->delivery_option_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tracking Number </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->tracking_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Package Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->package_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Total Amount </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->total_amount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Fee </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->shipping_fee, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Seller Discount </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->seller_discount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tiktok Discount </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_orders->tiktok_discount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Created Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_created_time); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Paid Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_orders->order_paid_time); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="content" class="col-sm-2 control-label">Produk Dipesan </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr>
                                        <th width="60" class="text-center">Foto</th>
                                        <th>Nama Produk / Varian</th>
                                        <th width="120">Harga Satuan</th>
                                        <th width="70" class="text-center">Qty</th>
                                        <th width="130">Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($order_items)): ?>
                                        <?php foreach ($order_items as $item): ?>
                                            <tr>
                                                <td class="text-center" style="vertical-align: middle;">
                                                    <?php if (!empty($item->sku_image)): ?>
                                                        <img src="<?= $item->sku_image; ?>" style="width: 44px; height: 44px; object-fit: cover; border-radius: 4px; border: 1px solid #ddd;" alt="item">
                                                    <?php else: ?>
                                                        <span class="text-muted">-</span>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="vertical-align: middle;">
                                                    <div><?= _ent($item->product_name); ?></div>
                                                    <?php if (!empty($item->sku_name) && $item->sku_name != 'Default'): ?>
                                                        <small class="text-muted">Varian: <?= _ent($item->sku_name); ?></small>
                                                    <?php endif; ?>
                                                    <?php if (!empty($item->seller_sku)): ?>
                                                        <br><small class="text-muted">SKU: <?= _ent($item->seller_sku); ?></small>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="vertical-align: middle;">Rp <?= number_format($item->item_price, 0, ',', '.'); ?></td>
                                                <td class="text-center" style="vertical-align: middle;"><?= $item->quantity; ?></td>
                                                <td style="vertical-align: middle;">Rp <?= number_format($item->item_price * $item->quantity, 0, ',', '.'); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <tr>
                                            <td colspan="5" class="text-center text-muted">Tidak ada rincian produk.</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Rincian Finansial Pesanan (Price Detail Breakdown) -->
                    <div class="form-group">
                        <label for="content" class="col-sm-2 control-label">Rincian Finansial Pesanan </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr class="bg-gray">
                                        <th>Komponen Finansial</th>
                                        <th style="width: 220px; text-align: right;">Jumlah (IDR)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($price_details)): ?>
                                        <tr>
                                            <td>Harga Asli Produk (Subtotal Kotor)</td>
                                            <td style="text-align: right;">Rp <?= number_format($price_details->original_product_price, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php if ($price_details->seller_discount > 0): ?>
                                        <tr>
                                            <td>Diskon Penjual</td>
                                            <td style="text-align: right; color: #dd4b39;">- Rp <?= number_format($price_details->seller_discount, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php endif; ?>
                                        <?php if ($price_details->platform_discount > 0): ?>
                                        <tr>
                                            <td>Diskon Platform TikTok</td>
                                            <td style="text-align: right; color: #0073b7;">- Rp <?= number_format($price_details->platform_discount, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php endif; ?>
                                        <tr>
                                            <td><strong>Subtotal Produk Bersih</strong></td>
                                            <td style="text-align: right;"><strong>Rp <?= number_format($price_details->subtotal, 0, ',', '.'); ?></strong></td>
                                        </tr>
                                        <tr>
                                            <td>Ongkos Kirim Asli</td>
                                            <td style="text-align: right;">Rp <?= number_format($price_details->original_shipping_fee, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php if ($price_details->shipping_fee_platform_discount > 0): ?>
                                        <tr>
                                            <td>Subsidi Ongkir Platform TikTok</td>
                                            <td style="text-align: right; color: #00a65a;">- Rp <?= number_format($price_details->shipping_fee_platform_discount, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php endif; ?>
                                        <?php if ($price_details->shipping_fee_seller_discount > 0): ?>
                                        <tr>
                                            <td>Diskon Ongkir Penjual</td>
                                            <td style="text-align: right; color: #dd4b39;">- Rp <?= number_format($price_details->shipping_fee_seller_discount, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php endif; ?>
                                        <tr>
                                            <td>Ongkos Kirim Dibayar Pembeli</td>
                                            <td style="text-align: right;">Rp <?= number_format($price_details->buyer_shipping_fee, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php if ($price_details->tax > 0): ?>
                                        <tr>
                                            <td>Pajak</td>
                                            <td style="text-align: right;">Rp <?= number_format($price_details->tax, 0, ',', '.'); ?></td>
                                        </tr>
                                        <?php endif; ?>
                                        <tr class="info">
                                            <td><strong>Total Pembayaran Pembeli</strong></td>
                                            <td style="text-align: right;"><strong>Rp <?= number_format($price_details->total_buyer_payment, 0, ',', '.'); ?></strong></td>
                                        </tr>
                                        <tr class="success" style="background-color: #dff0d8;">
                                            <td><strong>Estimasi Pendapatan Penjual</strong></td>
                                            <td style="text-align: right; color: #3c763d;"><strong>Rp <?= number_format($price_details->seller_revenue, 0, ',', '.'); ?></strong></td>
                                        </tr>
                                    <?php else: ?>
                                        <tr>
                                            <td>Subtotal Produk</td>
                                            <td style="text-align: right;">Rp <?= number_format($tiktok_orders->total_amount - $tiktok_orders->shipping_fee, 0, ',', '.'); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Ongkos Kirim</td>
                                            <td style="text-align: right;">Rp <?= number_format($tiktok_orders->shipping_fee, 0, ',', '.'); ?></td>
                                        </tr>
                                        <tr class="info">
                                            <td><strong>Total Pembayaran Pembeli</strong></td>
                                            <td style="text-align: right;"><strong>Rp <?= number_format($tiktok_orders->total_amount, 0, ',', '.'); ?></strong></td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Riwayat Perubahan Status (Status Logs) -->
                    <div class="form-group">
                        <label for="content" class="col-sm-2 control-label">Riwayat Status Pesanan </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr class="bg-gray">
                                        <th style="width: 170px;">Waktu</th>
                                        <th style="width: 150px;">Status Sebelumnya</th>
                                        <th style="width: 150px;">Status Baru</th>
                                        <th>Keterangan / Alasan</th>
                                        </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($status_logs)): ?>
                                        <?php 
                                        function render_log_status_badge($st) {
                                            $s = strtoupper(trim((string)$st));
                                            switch ($s) {
                                                case "UNPAID": return '<span class="label label-info">Belum Bayar</span>';
                                                case "ON_HOLD": return '<span class="label label-warning">Ditahan</span>';
                                                case "AWAITING_SHIPMENT": return '<span class="label label-warning">Perlu Dikirim</span>';
                                                case "AWAITING_COLLECTION": return '<span class="label label-info">Menunggu Kurir</span>';
                                                case "PARTIALLY_SHIPPING": return '<span class="label label-info">Sebagian Dikirim</span>';
                                                case "IN_TRANSIT": return '<span class="label label-info">Sedang Dikirim</span>';
                                                case "DELIVERED": return '<span class="label label-primary">Terkirim</span>';
                                                case "COMPLETED": return '<span class="label label-success">Selesai</span>';
                                                case "CANCELLED": return '<span class="label label-danger">Dibatalkan</span>';
                                                default: return $s ? '<span class="label label-info">' . _ent($s) . '</span>' : '<span class="text-muted">-</span>';
                                            }
                                        }
                                        ?>
                                        <?php foreach ($status_logs as $log): ?>
                                            <tr>
                                                <td style="vertical-align: middle; white-space: nowrap;"><?= date('d/m/Y H:i:s', strtotime($log->created_at)); ?></td>
                                                <td style="vertical-align: middle;"><?= render_log_status_badge($log->previous_status); ?></td>
                                                <td style="vertical-align: middle;"><?= render_log_status_badge($log->new_status); ?></td>
                                                <td style="vertical-align: middle;"><?= _ent($log->reason ?: '-'); ?></td>
                                                
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <tr>
                                            <td colspan="4" class="text-center text-muted">Belum ada riwayat perubahan status tercatat.</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php if ($tiktok_orders->order_status == 'AWAITING_SHIPMENT'): ?>
                           <a class="btn btn-flat btn-default btn_action" title="Atur Pengiriman (Drop-off ke gerai)" href="<?= site_url('administrator/tiktok_orders/ship/'.$tiktok_orders->id); ?>"><i class="fa fa-truck" ></i> Atur Pengiriman</a>
                        <?php elseif (in_array($tiktok_orders->order_status, ['AWAITING_COLLECTION', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED'])): ?>
                           <a class="btn btn-flat btn-default btn_action" target="_blank" title="Cetak Label Resi (AWB PDF)" href="<?= site_url('administrator/tiktok_orders/print_label/'.$tiktok_orders->id); ?>"><i class="fa fa-barcode" ></i> Cetak Label Resi</a>
                            <a class="btn btn-flat btn-default btn_action" target="_blank" title="Cetak Daftar Pengemasan (Packing List PDF)" href="<?= site_url('administrator/tiktok_orders/print_packing_slip/' . $tiktok_orders->id); ?>"><i class="fa fa-archive" ></i> Cetak Daftar Pengemasan</a>
                         <?php endif; ?>
                         <a class="btn btn-flat btn-default btn_action" target="_blank" title="Cetak Daftar Pengambilan Barang (Pick List)" href="<?= site_url('administrator/tiktok_orders/print_pick_list/' . $tiktok_orders->id); ?>"><i class="fa fa-clipboard" ></i> Cetak Pengambilan Barang</a>
                        <?php if ($tiktok_orders->order_status != 'CANCELLED'): ?>
                         <a class="btn btn-flat btn-default btn_action cancel-data" href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_orders/cancel/' . $tiktok_orders->id); ?>" title="Batalkan Pesanan"><i class="fa fa-ban" ></i> Batalkan Pesanan</a>
                         <?php endif; ?>
                         <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tiktok_orders/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tiktok Orders']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).on('click', '.cancel-data', function(){
  var url = $(this).attr('data-href');
  swal({
      title: 'Batalkan Pesanan?',
      text: 'Pesanan ini akan dibatalkan di TikTok Shop dan Vendio. Apakah Anda yakin?',
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#DD6B55',
      confirmButtonText: 'Ya, Batalkan!',
      cancelButtonText: 'Batal',
      closeOnConfirm: true,
      closeOnCancel: true
    },
    function(isConfirm){
      if (isConfirm) {
        document.location.href = url;
      }
    });
  return false;
});
</script>
