<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_orders') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tiktok_orders') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tiktok_orders_list', function(){?>
                                                <a class="btn btn-flat btn-success" id="btn_sync" title="Tarik Data Pesanan dari TikTok Shop" href="<?= site_url('administrator/tiktok_orders/sync'); ?>"><i class="fa fa-refresh" ></i> Tarik Data Pesanan</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_orders_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('tiktok_orders'); ?>" href="<?= site_url('administrator/tiktok_orders/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_orders_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> PDF <?= cclang('tiktok_orders'); ?>" href="<?= site_url('administrator/tiktok_orders/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_orders') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tiktok_orders')]); ?>  <i class="label bg-yellow"><?= $tiktok_orders_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tiktok_orders" id="form_tiktok_orders" action="<?= base_url('administrator/tiktok_orders/index'); ?>">

                  <div class="table-responsive" style="overflow-x: auto; width: 100%;"> 
                  <table class="table table-bordered table-striped dataTable" style="min-width: 1400px; width: 100%;">
                     <thead>
                        <tr style="white-space: nowrap;">
                           <th width="5">
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="Pilih Semua">
                           </th>
                           <th>Nama Toko</th>
                           <th>ID Pesanan</th>
                           <th>Nama Pembeli</th>
                           <th style="min-width: 320px;">Produk</th>
                           <th>Status Pesanan</th>
                           <th>Metode Pengiriman</th>
                           <th>Opsi Pengiriman</th>
                           <th>Total Pembayaran</th>
                           <th style="width: 260px; min-width: 260px; text-align: center;">Aksi</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_tiktok_orders">
                     <?php foreach($tiktok_orderss as $tiktok_orders): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tiktok_orders->id; ?>">
                           </td>
                           <td style="white-space: nowrap;">
                              <?php if ($tiktok_orders->tiktok_shop_id): ?>
                                 <?= anchor('administrator/tiktok_shops/view/'.$tiktok_orders->tiktok_shop_id.'?popup=show', $tiktok_orders->tiktok_shops_shop_name, ['class' => 'popup-view']); ?>
                              <?php else: ?>
                                 <span class="text-muted">-</span>
                              <?php endif; ?>
                           </td>                             
                           <td style="white-space: nowrap;">
                               <a href="<?= site_url('administrator/tiktok_orders/view/' . $tiktok_orders->id); ?>" style="color: #3c8dbc;"><?= _ent($tiktok_orders->order_id); ?></a>
                            </td> 
                           <td style="white-space: nowrap;">
                               <div><?= _ent($tiktok_orders->recipient_name ?: '-'); ?></div>
                               <?php if (!empty($tiktok_orders->recipient_phone)): ?>
                                  <small class="text-muted"><?= _ent($tiktok_orders->recipient_phone); ?></small>
                               <?php endif; ?>
                            </td> 
                           <td style="min-width: 320px;">
                              <?php if (!empty($tiktok_orders->items)): ?>
                                 <?php foreach ($tiktok_orders->items as $item): ?>
                                    <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
                                       <?php if (!empty($item->sku_image)): ?>
                                          <img src="<?= $item->sku_image; ?>" style="width: 42px; height: 42px; object-fit: cover; border-radius: 4px; border: 1px solid #ddd; flex-shrink: 0;" alt="item">
                                       <?php endif; ?>
                                       <div style="flex-grow: 1;">
                                           <div><?= _ent($item->product_name); ?></div>
                                           <?php if (!empty($item->seller_sku)): ?>
                                              <small class="text-muted">(SKU: <?= _ent($item->seller_sku); ?>)</small>
                                           <?php endif; ?>
                                        </div>
                                    </div>
                                 <?php endforeach; ?>
                              <?php else: ?>
                                 <span class="text-muted">-</span>
                              <?php endif; ?>
                           </td> 
                           <td style="white-space: nowrap;">
                              <?php
                                 $st = strtoupper($tiktok_orders->order_status);
                                 switch ($st) {
                                    case "UNPAID":
                                       echo '<span class="label label-info">Belum Bayar</span>';
                                       break;
                                    case "ON_HOLD":
                                       echo '<span class="label label-warning">Ditahan</span>';
                                       break;
                                    case "AWAITING_SHIPMENT":
                                       echo '<span class="label label-warning">Perlu Dikirim</span>';
                                       break;
                                    case "AWAITING_COLLECTION":
                                       echo '<span class="label label-info">Menunggu Kurir</span>';
                                       break;
                                     case "PARTIALLY_SHIPPING":
                                        echo '<span class="label label-info">Sebagian Dikirim</span>';
                                        break;
                                    case "IN_TRANSIT":
                                       echo '<span class="label label-info">Sedang Dikirim</span>';
                                       break;
                                    case "DELIVERED":
                                       echo '<span class="label label-primary">Terkirim</span>';
                                       break;
                                    case "COMPLETED":
                                       echo '<span class="label label-success">Selesai</span>';
                                       break;
                                    case "CANCELLED":
                                       echo '<span class="label label-danger">Dibatalkan</span>';
                                       break;
                                    default:
                                       echo '<span class="label label-info">' . _ent($tiktok_orders->order_status) . '</span>';
                                 }
                              ?>
                           </td> 
                            <td style="white-space: nowrap;">
                               <div><?= _ent($tiktok_orders->shipping_type ?: '-'); ?></div>
                               <?php if (!empty($tiktok_orders->shipping_provider)): ?>
                                  <small class="text-muted"><?= _ent($tiktok_orders->shipping_provider); ?></small>
                               <?php endif; ?>
                            </td>
                           <td style="white-space: nowrap;"><?= _ent($tiktok_orders->delivery_option_name ?: '-'); ?></td> 
                           <td style="white-space: nowrap;">Rp <?= number_format($tiktok_orders->total_amount, 0, ',', '.'); ?></td> 
                           <td style="min-width: 260px; text-align: center;">
                              <?php is_allowed('tiktok_orders_view', function() use ($tiktok_orders){?>
                                 <?php if ($tiktok_orders->order_status == 'AWAITING_SHIPMENT'): ?>
                                    <a href="<?= site_url('administrator/tiktok_orders/ship/' . $tiktok_orders->id); ?>" class="label-default" title="Atur Pengiriman (Drop-off ke gerai)"><i class="fa fa-truck"></i> Kirim</a>
                                 <?php elseif (in_array($tiktok_orders->order_status, ['AWAITING_COLLECTION', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED'])): ?>
                                     <a href="<?= site_url('administrator/tiktok_orders/print_label/' . $tiktok_orders->id); ?>" target="_blank" class="label-default" title="Cetak Label Resi Pengiriman (AWB PDF)"><i class="fa fa-barcode"></i> Label</a>
                                     <a href="<?= site_url('administrator/tiktok_orders/print_packing_slip/' . $tiktok_orders->id); ?>" target="_blank" class="label-default" title="Cetak Daftar Pengemasan (Packing List PDF)"><i class="fa fa-archive"></i> Pengemasan</a>
                                  <?php endif; ?>
                                  <a href="<?= site_url('administrator/tiktok_orders/print_pick_list/' . $tiktok_orders->id); ?>" target="_blank" class="label-default" title="Cetak Daftar Pengambilan Barang (Pick List)"><i class="fa fa-clipboard"></i> Pengambilan</a>
                                 <a href="<?= site_url('administrator/tiktok_orders/single_pdf/' .$tiktok_orders->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?></a>
                                 <a href="<?= site_url('administrator/tiktok_orders/view/' . $tiktok_orders->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('tiktok_orders_delete', function() use ($tiktok_orders){?>
                                 <?php if ($tiktok_orders->order_status != 'CANCELLED'): ?>
                                     <a href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_orders/cancel/' . $tiktok_orders->id); ?>" class="label-default cancel-data" title="Batalkan Pesanan"><i class="fa fa-ban"></i> Batalkan</a>
                                  <?php endif; ?>
                              <?php }) ?>
                           </td>
                        </tr>
                     <?php endforeach; ?>
                     <?php if ($tiktok_orders_counts == 0) :?>
                        <tr>
                          <td colspan="100" class="text-center text-muted" style="padding: 20px;">
                          Belum ada data pesanan TikTok
                          </td>
                        </tr>
                     <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="cancel">Batalkan</option>
                           <option value="pick_list">Cetak Daftar Pengambilan (Pick List)</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                            <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'order_id' ? 'selected' :''; ?> value="order_id">ID Pesanan</option>
                            <option <?= $this->input->get('f') == 'tiktok_shop_id' ? 'selected' :''; ?> value="tiktok_shop_id">Nama Toko</option>
                            <option <?= $this->input->get('f') == 'recipient_name' ? 'selected' :''; ?> value="recipient_name">Nama Pembeli</option>
                            <option <?= $this->input->get('f') == 'order_status' ? 'selected' :''; ?> value="order_status">Status Pesanan</option>
                            <option <?= $this->input->get('f') == 'shipping_type' ? 'selected' :''; ?> value="shipping_type">Metode Pengiriman</option>
                            <option <?= $this->input->get('f') == 'delivery_option_name' ? 'selected' :''; ?> value="delivery_option_name">Opsi Pengiriman</option>
                            <option <?= $this->input->get('f') == 'shipping_provider' ? 'selected' :''; ?> value="shipping_provider">Kurir Pengiriman</option>
                            <option <?= $this->input->get('f') == 'tracking_number' ? 'selected' :''; ?> value="tracking_number">Nomor Resi</option>
                         </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tiktok_orders');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $(document).on('click', '.cancel-data', function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Batalkan Pesanan?",
          text: "Pesanan ini akan dibatalkan di TikTok Shop dan Vendio. Apakah Anda yakin?",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Ya, Batalkan!",
          cancelButtonText: "Batal",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tiktok_orders').serialize();

      if (bulk.val() == 'pick_list') {
        var checked_ids = [];
        $('input.check:checked').each(function(){
            checked_ids.push($(this).val());
        });
        if (checked_ids.length == 0) {
            swal('Peringatan', 'Silakan pilih minimal 1 pesanan untuk dicetak!', 'warning');
            return false;
        }
        window.open(BASE_URL + '/administrator/tiktok_orders/print_bulk_pick_list?ids=' + checked_ids.join(','), '_blank');
        return false;
      } else if (bulk.val() == 'cancel' || bulk.val() == 'delete') {
         swal({
            title: "Batalkan Pesanan Terpilih?",
            text: "Semua pesanan terpilih akan dibatalkan di TikTok Shop dan Vendio. Lanjutkan?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tiktok_orders/cancel?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '') {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning"
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>