
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tiktok_shops/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_shops') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tiktok_shops') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tiktok_shops_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('tiktok_shops')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tiktok_shops/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('tiktok_shops')]); ?></a>
                        <a class="btn btn-flat btn-success" id="btn_connect_tiktok" target="_blank" title="Hubungkan Akun TikTok Shop" href="<?= site_url('administrator/tiktok_shops/connect'); ?>"><i class="fa fa-plug"></i> Hubungkan Akun TikTok</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_shops_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('tiktok_shops') ?>']); ?>" href="<?= site_url('administrator/tiktok_shops/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_shops_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('tiktok_shops') ?>']); ?>" href="<?= site_url('administrator/tiktok_shops/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_shops') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tiktok_shops')]); ?>  <i class="label bg-yellow"><?= $tiktok_shops_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tiktok_shops" id="form_tiktok_shops" action="<?= base_url('administrator/tiktok_shops/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                      <thead>
                         <tr>
                            <th style="width: 40px; text-align: center;">
                               <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="Pilih Semua">
                            </th>
                            <th style="width: 25%;">Nama Toko</th>
                            <th style="width: 20%;">ID Toko</th>
                            <th style="width: 12%; text-align: center;">Wilayah</th>
                            <th style="width: 18%;">Masa Berlaku Token</th>
                            <th style="width: 10%; text-align: center;">Status</th>
                            <th style="width: 15%; min-width: 160px; text-align: center;">Aksi</th>
                         </tr>
                      </thead>
                     <tbody id="tbody_tiktok_shops">
                     <?php foreach($tiktok_shopss as $tiktok_shops): ?>
                        <tr>
                            <td style="text-align: center;">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tiktok_shops->id; ?>">
                           </td>
                                                       
                            <td><?= _ent($tiktok_shops->shop_name); ?></td>
                            <td><?= _ent($tiktok_shops->shop_id); ?></td>
                            <td style="text-align: center;"><?= _ent($tiktok_shops->seller_base_region); ?></td>
                           <td>
                               <?= !empty($tiktok_shops->access_token_expire_in) ? date('d F Y H:i:s', $tiktok_shops->access_token_expire_in) : '-'; ?>
                            </td> 
                            <td style="text-align: center;">
                              <?= $tiktok_shops->is_active == 1 
                                 ? '<span class="label label-success"><i class="fa fa-check"></i> Aktif</span>' 
                                 : '<span class="label label-danger"><i class="fa fa-ban"></i> Nonaktif</span>'; ?>
                           </td> 
                            <td style="text-align: center;">
                            
                                                              <?php is_allowed('tiktok_shops_view', function() use ($tiktok_shops){?>
                                 <a href="<?= site_url('administrator/tiktok_shops/single_pdf/' .$tiktok_shops->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/tiktok_shops/view/' . $tiktok_shops->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('tiktok_shops_update', function() use ($tiktok_shops){?>
                              <a href="<?= site_url('administrator/tiktok_shops/edit/' . $tiktok_shops->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                               <a href="<?= site_url('administrator/tiktok_shops/refresh_token/' . $tiktok_shops->id); ?>" class="label-default"><i class="fa fa-refresh"></i> Refresh Token</a>
                              <?php }) ?>
                              <?php is_allowed('tiktok_shops_delete', function() use ($tiktok_shops){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_shops/delete/' . $tiktok_shops->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tiktok_shops_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                            Data Kelola Toko belum tersedia
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'shop_id' ? 'selected' :''; ?> value="shop_id">Shop Id</option>
                           <option <?= $this->input->get('f') == 'shop_name' ? 'selected' :''; ?> value="shop_name">Shop Name</option>
                           <option <?= $this->input->get('f') == 'seller_base_region' ? 'selected' :''; ?> value="seller_base_region">Seller Base Region</option>
                           <option <?= $this->input->get('f') == 'access_token_expire_in' ? 'selected' :''; ?> value="access_token_expire_in">Access Token Expire In</option>
                           <option <?= $this->input->get('f') == 'is_active' ? 'selected' :''; ?> value="is_active">Is Active</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tiktok_shops');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tiktok_shops').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tiktok_shops/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>