<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+e', function assets() {
         $('#btn_edit').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#btn_back').trigger('click');
         return false;
      });

   }


   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Kelola Toko <small><?= cclang('detail', ['Kelola Toko']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a href="<?= site_url('administrator/tiktok_shops'); ?>">Kelola Toko</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">

                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Kelola Toko</h3>
                     <h5 class="widget-user-desc">Detail Kelola Toko</h5>
                     <hr>
                  </div>


                  <div class="form-horizontal" name="form_tiktok_shops" id="form_tiktok_shops">

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shop Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->shop_id); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shop Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->shop_name); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shop Code </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->shop_code); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shop Cipher </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->shop_cipher); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Seller Type </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->seller_type); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Seller Base Region </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->seller_base_region); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Seller Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->seller_name); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Open Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->open_id); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Auth Code </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->auth_code); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Access Token </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->access_token); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Access Token Expired </label>

                        <div class="col-sm-8" style="padding-top: 7px;">
                           <?= !empty($tiktok_shops->access_token_expire_in) ? date('d F Y H:i:s', $tiktok_shops->access_token_expire_in) : '-'; ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Refresh Token </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_shops->refresh_token); ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Refresh Token Expired </label>

                        <div class="col-sm-8" style="padding-top: 7px;">
                           <?= !empty($tiktok_shops->refresh_token_expire_in) ? date('d F Y H:i:s', $tiktok_shops->refresh_token_expire_in) : '-'; ?>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Toko </label>
                        <div class="col-sm-8" style="padding-top: 7px;">
                           <?= $tiktok_shops->is_active == 1 
                              ? '<span class="label label-success"><i class="fa fa-check"></i> Aktif</span>' 
                              : '<span class="label label-danger"><i class="fa fa-ban"></i> Nonaktif</span>'; ?>
                        </div>
                     </div>

                     <br>
                     <br>

                     <div class="view-nav">
                        <?php is_allowed('tiktok_shops_update', function () use ($tiktok_shops) { ?>
                           <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back'
                              title="edit tiktok_shops (Ctrl+e)"
                              href="<?= site_url('administrator/tiktok_shops/edit/' . $tiktok_shops->id); ?>"><i
                                 class="fa fa-edit"></i> <?= cclang('update', ['Tiktok Shops']); ?> </a>
                            <a class="btn btn-flat btn-warning btn_action" id="btn_refresh_token" title="Refresh Token" href="<?= site_url('administrator/tiktok_shops/refresh_token/' . $tiktok_shops->id); ?>"><i class="fa fa-refresh"></i> Refresh Token</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)"
                           href="<?= site_url('administrator/tiktok_shops/'); ?>"><i class="fa fa-undo"></i>
                           <?= cclang('go_list_button', ['Tiktok Shops']); ?></a>
                     </div>

                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->