CREATE TABLE IF NOT EXISTS `tiktok_shops` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shop_id` VARCHAR(100) DEFAULT NULL,
  `shop_name` VARCHAR(255) DEFAULT NULL,
  `shop_code` VARCHAR(100) DEFAULT NULL,
  `shop_cipher` VARCHAR(255) DEFAULT NULL,
  `seller_type` VARCHAR(50) DEFAULT 'LOCAL',
  `seller_base_region` VARCHAR(20) DEFAULT 'ID',
  `seller_name` VARCHAR(255) DEFAULT NULL,
  `open_id` VARCHAR(255) DEFAULT NULL,
  `app_key` VARCHAR(100) NOT NULL,
  `app_secret` VARCHAR(255) NOT NULL,
  `auth_code` VARCHAR(255) DEFAULT NULL,
  `access_token` TEXT DEFAULT NULL,
  `access_token_expire_in` BIGINT DEFAULT NULL,
  `refresh_token` TEXT DEFAULT NULL,
  `refresh_token_expire_in` BIGINT DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_shop_id` (`shop_id`),
  KEY `idx_shop_cipher` (`shop_cipher`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
