
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Merek Produk      <small><?= cclang('detail', ['Merek Produk']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tiktok_brands'); ?>">Merek Produk</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Merek Produk</h3>
                     <h5 class="widget-user-desc">Detail Merek Produk</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_brands" id="form_tiktok_brands" >
                    
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_brands->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Merek (Brand) </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_brands->name); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Merek TikTok </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_brands->tiktok_brand_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Kategori </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_brands->category_id ?: "-"); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Otorisasi </label>
                        <div class="col-sm-8">
                           <?= $tiktok_brands->is_authorized ? '<span class="label label-success">Terotorisasi</span>' : '<span class="label label-danger">Belum Terotorisasi</span>'; ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="Kembali ke Daftar Merek" href="<?= site_url('administrator/tiktok_brands/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Merek']); ?></a>
                    </div>
                  </div>
</div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
