
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Kategori Produk      <small><?= cclang('detail', ['Kategori Produk']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tiktok_categories'); ?>">Kategori Produk</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Kategori Produk</h3>
                     <h5 class="widget-user-desc">Detail Kategori Produk</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_categories" id="form_tiktok_categories" >
                    
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_categories->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Kategori </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_categories->local_name); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Kategori TikTok </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_categories->tiktok_category_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Induk Kategori </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_categories->parent_category_id ?: "-"); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tingkat (Level) </label>
                        <div class="col-sm-8">
                           Level <?= _ent($tiktok_categories->level); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tipe Kategori </label>
                        <div class="col-sm-8">
                           <?= $tiktok_categories->is_leaf ? "Leaf Kategori" : "Induk Kategori"; ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Izin </label>
                        <div class="col-sm-8">
                           <?= strtoupper($tiktok_categories->permission_status) == "AVAILABLE" ? '<span class="label label-success">Tersedia</span>' : '<span class="label label-warning">Dibatasi</span>'; ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Versi Kategori </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_categories->category_version ?: "-"); ?>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 20px;">
                        <div class="col-sm-12">
                           <h4><i class="fa fa-list-ul"></i> Atribut Spesifik Kategori TikTok</h4>
                           <div class="table-responsive">
                              <table class="table table-bordered table-striped">
                                 <thead>
                                    <tr>
                                       <th>Nama Atribut</th>
                                       <th>ID Atribut</th>
                                       <th>Tipe Input</th>
                                       <th>Wajib Diisi</th>
                                       <th>Pilihan Nilai</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    <?php if (!empty($tiktok_categories->attributes)): ?>
                                       <?php foreach ($tiktok_categories->attributes as $attr): ?>
                                          <?php 
                                             $vals = [];
                                             if (!empty($attr->values_json)) {
                                                $decoded = json_decode($attr->values_json, true);
                                                if (is_array($decoded)) {
                                                   foreach ($decoded as $val_item) {
                                                      $vals[] = $val_item['name'] ?? $val_item['id'] ?? '';
                                                   }
                                                }
                                             }
                                          ?>
                                          <tr>
                                             <td><strong><?= _ent($attr->attribute_name); ?></strong></td>
                                             <td><code><?= _ent($attr->tiktok_attribute_id); ?></code></td>
                                             <td><?= _ent($attr->attribute_type ?: 'TEXT'); ?></td>
                                             <td><?= $attr->is_required ? '<span class="label label-danger">Wajib</span>' : '<span class="label label-info">Opsional</span>'; ?></td>
                                             <td>
                                                <?php if (!empty($vals)): ?>
                                                   <small><?= _ent(implode(', ', array_slice($vals, 0, 8))); ?><?= count($vals) > 8 ? ' ... (total ' . count($vals) . ')' : ''; ?></small>
                                                <?php else: ?>
                                                   <em class="text-muted">Input bebas / dinamis</em>
                                                <?php endif; ?>
                                             </td>
                                          </tr>
                                       <?php endforeach; ?>
                                    <?php else: ?>
                                       <tr>
                                          <td colspan="5" class="text-center text-muted">
                                             <?php if (!empty($tiktok_categories->is_leaf)): ?>
                                                Belum ada atribut tercatat untuk leaf kategori ini.
                                             <?php else: ?>
                                                Kategori ini bukan level <em>leaf</em> (memiliki sub-kategori). Atribut produk hanya tersedia pada level leaf kategori.
                                             <?php endif; ?>
                                          </td>
                                       </tr>
                                    <?php endif; ?>
                                 </tbody>
                              </table>
                           </div>
                        </div>
                    </div>
                    <br>

                    <div class="view-nav">
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="Kembali ke Daftar Kategori" href="<?= site_url('administrator/tiktok_categories/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Kategori']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
