
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Blog/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>

<style>
/* Action Dropdown 3-Dots Component */
.action-dropdown {
   position: relative;
   display: inline-block;
}

.btn-action-dots,
.btn-action-dropdown {
   display: inline-flex !important;
   align-items: center !important;
   justify-content: center !important;
   width: 32px !important;
   height: 32px !important;
   min-width: 32px !important;
   padding: 0 !important;
   font-size: 15px !important;
   color: #475569 !important;
   background-color: #ffffff !important;
   border: 1px solid #cbd5e1 !important;
   border-radius: 6px !important;
   cursor: pointer !important;
   outline: none !important;
   box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04) !important;
   transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1) !important;
}

.btn-action-dots:hover,
.btn-action-dots:focus,
.btn-action-dropdown:hover,
.btn-action-dropdown:focus {
   background-color: #f8fafc !important;
   border-color: #94a3b8 !important;
   color: #0f172a !important;
   box-shadow: 0 2px 5px rgba(0, 0, 0, 0.08) !important;
}

.action-dropdown.open .btn-action-dots,
.action-dropdown.open .btn-action-dropdown {
   background-color: #ffffff !important;
   border-color: #00a65a !important;
   color: #00a65a !important;
   box-shadow: 0 0 0 2.5px rgba(0, 166, 90, 0.15) !important;
}

.action-dropdown .action-dropdown-menu {
   position: absolute !important;
   top: calc(100% + 5px) !important;
   right: 0 !important;
   left: auto !important;
   min-width: 170px !important;
   padding: 6px 0 !important;
   margin: 0 !important;
   background: #ffffff !important;
   border: 1px solid #e2e8f0 !important;
   border-radius: 8px !important;
   box-shadow: 0 10px 25px -5px rgba(15, 23, 42, 0.1), 0 8px 10px -6px rgba(15, 23, 42, 0.06) !important;
   list-style: none !important;
   z-index: 1050 !important;
   text-align: left !important;
   display: block !important;
   opacity: 0;
   visibility: hidden;
   transform: translateY(-8px) scale(0.97);
   transform-origin: top right;
   pointer-events: none;
   transition: opacity 0.2s cubic-bezier(0.16, 1, 0.3, 1),
               transform 0.2s cubic-bezier(0.16, 1, 0.3, 1),
               visibility 0.2s cubic-bezier(0.16, 1, 0.3, 1);
}

.action-dropdown.open .action-dropdown-menu {
   opacity: 1 !important;
   visibility: visible !important;
   transform: translateY(0) scale(1) !important;
   pointer-events: auto !important;
}

.action-dropdown-menu li {
   margin: 0 !important;
   padding: 0 !important;
}

.action-dropdown-menu .dropdown-item-action {
   display: flex !important;
   align-items: center !important;
   gap: 9px !important;
   padding: 7px 14px !important;
   font-size: 12.5px !important;
   font-weight: 500 !important;
   color: #334155 !important;
   text-decoration: none !important;
   line-height: 1.4 !important;
   transition: background-color 0.15s ease, color 0.15s ease, padding-left 0.15s ease !important;
   clear: both;
   white-space: nowrap;
}

.action-dropdown-menu .dropdown-item-action i {
   width: 16px;
   text-align: center;
   font-size: 13px;
   flex-shrink: 0;
}

.action-dropdown-menu .dropdown-item-action:hover {
   background-color: #f1f5f9 !important;
   color: #0f172a !important;
   padding-left: 17px !important;
}

.action-dropdown-menu .dropdown-item-action.item-danger {
   color: #e11d48 !important;
}

.action-dropdown-menu .dropdown-item-action.item-danger:hover {
   background-color: #fef2f2 !important;
   color: #be123c !important;
   padding-left: 17px !important;
}

/* Main Card Wrapper */
.box-blog {
   border-radius: 8px;
   border: 1px solid #e5e9f0 !important;
   box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04) !important;
   background: #ffffff;
   margin-top: 14px;
   margin-bottom: 25px;
}

/* Header with Generous & Balanced Spacing */
.box-blog .widget-user-header {
   display: flex !important;
   align-items: center !important;
   justify-content: space-between !important;
   padding: 22px 25px !important;
   border-bottom: 1px solid #edf2f7 !important;
   background: #ffffff !important;
   flex-wrap: wrap !important;
   gap: 16px !important;
}

.box-blog .header-left {
   display: flex !important;
   align-items: center !important;
   gap: 20px !important;
}

.box-blog .widget-user-image {
   width: 52px !important;
   height: 52px !important;
   flex-shrink: 0 !important;
   margin: 0 !important;
   padding: 0 !important;
   float: none !important;
   display: flex !important;
   align-items: center !important;
   justify-content: center !important;
}

.box-blog .widget-user-image img {
   width: 52px !important;
   height: 52px !important;
   border-radius: 50% !important;
   display: block !important;
   box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08) !important;
   float: none !important;
   margin: 0 !important;
}

.box-blog .header-titles {
   display: flex !important;
   flex-direction: column !important;
   justify-content: center !important;
   margin-left: 0 !important;
}

.box-blog .widget-user-username {
   font-size: 20px !important;
   font-weight: 700 !important;
   color: #1e293b !important;
   margin: 0 0 5px 0 !important;
   line-height: 1.2 !important;
}

.box-blog .widget-user-desc {
   font-size: 13px !important;
   color: #64748b !important;
   margin: 0 !important;
   display: flex !important;
   align-items: center !important;
   gap: 10px !important;
}

.box-blog .widget-user-desc .label {
   font-size: 11px !important;
   padding: 3px 9px !important;
   border-radius: 12px !important;
   font-weight: 600 !important;
   margin-left: 2px !important;
}

/* Header Top Action Buttons */
.box-blog .header-right {
   display: flex;
   align-items: center;
   gap: 8px;
   flex-wrap: wrap;
}

.box-blog .btn-top-action {
   height: 34px !important;
   padding: 0 14px !important;
   font-size: 12px !important;
   font-weight: 600 !important;
   border-radius: 4px !important;
   background-color: #00a65a !important;
   border: 1px solid #008d4c !important;
   color: #ffffff !important;
   display: inline-flex !important;
   align-items: center !important;
   gap: 6px !important;
   transition: all 0.15s ease;
   text-decoration: none !important;
}

.box-blog .btn-top-action:hover {
   background-color: #008d4c !important;
   box-shadow: 0 2px 6px rgba(0, 166, 90, 0.25);
   color: #ffffff !important;
}

/* Stat Cards Overview Grid */
.blog-stats-grid {
   display: grid;
   grid-template-columns: repeat(4, 1fr);
   gap: 16px;
   margin-bottom: 20px;
}

@media (max-width: 992px) {
   .blog-stats-grid {
      grid-template-columns: repeat(2, 1fr);
   }
}

@media (max-width: 576px) {
   .blog-stats-grid {
      grid-template-columns: 1fr;
   }
}

.stat-card-item {
   background: #ffffff;
   border: 1px solid #e5e9f0;
   border-radius: 8px;
   padding: 16px 20px;
   display: flex;
   align-items: center;
   gap: 16px;
   box-shadow: 0 1px 3px rgba(0, 0, 0, 0.03);
   transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.stat-card-item:hover {
   transform: translateY(-2px);
   box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06);
}

.stat-icon-wrapper {
   width: 46px;
   height: 46px;
   border-radius: 10px;
   display: flex;
   align-items: center;
   justify-content: center;
   font-size: 20px;
   flex-shrink: 0;
}

.stat-icon-blue {
   background-color: #eff6ff;
   color: #2563eb;
}

.stat-icon-green {
   background-color: #f0fdf4;
   color: #16a34a;
}

.stat-icon-amber {
   background-color: #fffbeb;
   color: #d97706;
}

.stat-icon-purple {
   background-color: #faf5ff;
   color: #9333ea;
}

.stat-card-info {
   display: flex;
   flex-direction: column;
}

.stat-card-value {
   font-size: 22px;
   font-weight: 700;
   color: #0f172a;
   line-height: 1.2;
}

.stat-card-label {
   font-size: 13px;
   font-weight: 600;
   color: #475569;
   margin-bottom: 2px;
}

.stat-card-subtext {
   font-size: 11.5px;
   color: #94a3b8;
}

/* Clean Table Styling */
.box-blog .table-responsive {
   border: none;
   margin: 0;
   overflow: visible !important;
}

.box-blog .table-minimal {
   table-layout: auto;
   width: 100%;
   border-collapse: collapse;
   margin-bottom: 0;
}

.box-blog .table-minimal thead th {
   background-color: #f8fafc;
   color: #64748b;
   font-size: 11px;
   font-weight: 700;
   text-transform: uppercase;
   letter-spacing: 0.04em;
   border-top: none;
   border-bottom: 2px solid #e2e8f0;
   border-left: none;
   border-right: none;
   padding: 12px 14px;
   vertical-align: middle;
}

.box-blog .table-minimal tbody td {
   border-top: 1px solid #f1f5f9;
   border-bottom: none;
   border-left: none;
   border-right: none;
   padding: 12px 14px;
   font-size: 13px;
   color: #334155;
   vertical-align: middle;
}

.box-blog .table-minimal tbody tr {
   position: relative;
   transition: background-color 0.15s ease;
}

.box-blog .table-minimal tbody tr:hover {
   background-color: #fbfcfd;
}

.box-blog .table-minimal tbody tr.dropdown-open {
   z-index: 50;
}

/* Chips & Badges */
.badge-category {
   background-color: #f1f5f9;
   color: #475569;
   font-size: 11.5px;
   font-weight: 600;
   padding: 4px 10px;
   border-radius: 6px;
   display: inline-block;
}

.badge-status-publish {
   background-color: #ecfdf5;
   color: #059669;
   border: 1px solid #a7f3d0;
   font-size: 11.5px;
   font-weight: 600;
   padding: 3px 9px;
   border-radius: 12px;
   display: inline-flex;
   align-items: center;
   gap: 5px;
}

.badge-status-draft {
   background-color: #fffbeb;
   color: #d97706;
   border: 1px solid #fde68a;
   font-size: 11.5px;
   font-weight: 600;
   padding: 3px 9px;
   border-radius: 12px;
   display: inline-flex;
   align-items: center;
   gap: 5px;
}

.badge-status-archive {
   background-color: #f1f5f9;
   color: #64748b;
   border: 1px solid #e2e8f0;
   font-size: 11.5px;
   font-weight: 600;
   padding: 3px 9px;
   border-radius: 12px;
   display: inline-flex;
   align-items: center;
   gap: 5px;
}

.chip-slug {
   font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
   font-size: 11.5px;
   color: #0284c7;
   background-color: #f0f9ff;
   border: 1px solid #bae6fd;
   padding: 2px 7px;
   border-radius: 4px;
   display: inline-flex;
   align-items: center;
   gap: 4px;
   text-decoration: none !important;
}

.chip-slug:hover {
   background-color: #e0f2fe;
   color: #0369a1;
}

.blog-title-cell {
   display: flex;
   flex-direction: column;
   gap: 4px;
}

.blog-title-text {
   font-weight: 600;
   color: #1e293b;
   font-size: 13.5px;
   line-height: 1.35;
}

.blog-author-tag {
   display: inline-flex;
   align-items: center;
   gap: 5px;
   color: #475569;
   font-size: 12.5px;
}

.blog-thumb-img {
   width: 44px;
   height: 44px;
   object-fit: cover;
   border-radius: 6px;
   border: 1px solid #e2e8f0;
   display: block;
   transition: transform 0.15s ease;
}

.blog-thumb-img:hover {
   transform: scale(1.05);
}

.blog-thumb-placeholder {
   width: 44px;
   height: 44px;
   border-radius: 6px;
   background-color: #f1f5f9;
   border: 1px solid #e2e8f0;
   display: flex;
   align-items: center;
   justify-content: center;
   color: #94a3b8;
   font-size: 16px;
}
</style>

<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Blog<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Blog</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <!-- Stats Overview Cards -->
   <div class="blog-stats-grid">
      <div class="stat-card-item">
         <div class="stat-icon-wrapper stat-icon-blue">
            <i class="fa fa-newspaper-o"></i>
         </div>
         <div class="stat-card-info">
            <span class="stat-card-value"><?= number_format($total_articles ?? $blog_counts, 0, ',', '.'); ?></span>
            <span class="stat-card-label">Total Artikel</span>
            <span class="stat-card-subtext">Semua postingan blog</span>
         </div>
      </div>
      <div class="stat-card-item">
         <div class="stat-icon-wrapper stat-icon-green">
            <i class="fa fa-check-circle"></i>
         </div>
         <div class="stat-card-info">
            <span class="stat-card-value"><?= number_format($published_count ?? 0, 0, ',', '.'); ?></span>
            <span class="stat-card-label">Artikel Terbit</span>
            <span class="stat-card-subtext">Aktif dan dapat dibaca</span>
         </div>
      </div>
      <div class="stat-card-item">
         <div class="stat-icon-wrapper stat-icon-amber">
            <i class="fa fa-pencil-square-o"></i>
         </div>
         <div class="stat-card-info">
            <span class="stat-card-value"><?= number_format($draft_count ?? 0, 0, ',', '.'); ?></span>
            <span class="stat-card-label">Draft / Review</span>
            <span class="stat-card-subtext">Belum dipublikasikan</span>
         </div>
      </div>
      <div class="stat-card-item">
         <div class="stat-icon-wrapper stat-icon-purple">
            <i class="fa fa-folder-open-o"></i>
         </div>
         <div class="stat-card-info">
            <span class="stat-card-value"><?= number_format($categories_count ?? 0, 0, ',', '.'); ?></span>
            <span class="stat-card-label">Kategori</span>
            <span class="stat-card-subtext">Kategori artikel blog</span>
         </div>
      </div>
   </div>

   <div class="row">
      
      <div class="col-md-12">
         <div class="box box-blog">
            <div class="box-body" style="padding: 0;">
               <!-- Widget: user widget style 1 -->
               <div class="box-widget widget-user-2" style="margin-bottom: 0;">
                  <div class="widget-user-header">
                     <div class="header-left">
                        <div class="widget-user-image">
                           <img src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                        </div>
                        <div class="header-titles">
                           <h3 class="widget-user-username">Blog</h3>
                           <h5 class="widget-user-desc">
                              <?= cclang('list_all', ['Blog']); ?> 
                              <span class="label bg-yellow"><?= $blog_counts; ?> <?= cclang('items'); ?></span>
                           </h5>
                        </div>
                     </div>

                     <div class="header-right">
                        <?php is_allowed('blog_add', function(){?>
                        <a class="btn btn-top-action btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Blog']); ?> (Ctrl+a)" href="<?= site_url('administrator/blog/add'); ?>">
                           <i class="fa fa-plus-square-o"></i> <?= cclang('add_new_button', ['Blog']); ?>
                        </a>
                        <?php }) ?>
                     </div>
                  </div>

                  <form name="form_blog" id="form_blog" action="<?= base_url('administrator/blog/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-minimal">
                     <thead>
                        <tr>
                           <th style="width: 40px; text-align: center;">
                              <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="<?= cclang('check_all'); ?>">
                           </th>
                           <th style="width: 65px; text-align: center;">Gambar</th>
                           <th style="min-width: 250px;">Judul & Slug</th>
                           <th style="width: 150px;">Kategori</th>
                           <th style="width: 120px; text-align: center;">Status</th>
                           <th style="width: 130px;">Penulis</th>
                           <th style="width: 130px;">Dibuat</th>
                           <th style="width: 48px; text-align: center;">Aksi</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_blog">
                     <?php foreach($blogs as $blog): ?>
                        <tr>
                           <td style="text-align: center;">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $blog->id; ?>">
                           </td>

                           <td style="text-align: center;">
                              <?php 
                              $images = !empty($blog->image) ? explode(',', $blog->image) : [];
                              $first_image = !empty($images[0]) ? trim($images[0]) : '';
                              if (!empty($first_image)):
                                 if (is_image($first_image)): ?>
                                    <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/blog/' . $first_image; ?>">
                                       <img src="<?= BASE_URL . 'uploads/blog/' . $first_image; ?>" class="blog-thumb-img" alt="<?= _ent($blog->title); ?>">
                                    </a>
                                 <?php else: ?>
                                    <a href="<?= BASE_URL . 'administrator/file/download/blog/' . $first_image; ?>">
                                       <img src="<?= get_icon_file($first_image); ?>" class="blog-thumb-img" alt="file">
                                    </a>
                                 <?php endif; ?>
                              <?php else: ?>
                                 <div class="blog-thumb-placeholder">
                                    <i class="fa fa-picture-o"></i>
                                 </div>
                              <?php endif; ?>
                           </td>
                           <td>
                              <div class="blog-title-cell">
                                 <span class="blog-title-text"><?= _ent($blog->title); ?></span>
                                 <a href="<?= site_url('blog/' . $blog->slug); ?>" target="_blank" class="chip-slug">
                                    <i class="fa fa-link"></i> /<?= _ent($blog->slug); ?>
                                 </a>
                              </div>
                           </td>
                           <td>
                              <span class="badge-category"><?= _ent(!empty($blog->category_name) ? $blog->category_name : 'Uncategorized'); ?></span>
                           </td>
                           <td style="text-align: center;">
                              <?php 
                              $status = strtolower(trim((string)$blog->status));
                              if ($status == 'publish' || $status == 'published'): ?>
                                 <span class="badge-status-publish"><i class="fa fa-circle" style="font-size: 7px;"></i> Publish</span>
                              <?php elseif ($status == 'draft'): ?>
                                 <span class="badge-status-draft"><i class="fa fa-circle" style="font-size: 7px;"></i> Draft</span>
                              <?php else: ?>
                                 <span class="badge-status-archive"><i class="fa fa-circle" style="font-size: 7px;"></i> <?= _ent(ucfirst($status)); ?></span>
                              <?php endif; ?>
                           </td>
                           <td>
                              <span class="blog-author-tag">
                                 <i class="fa fa-user-circle-o text-muted"></i> <?= _ent($blog->author); ?>
                              </span>
                           </td>
                           <td>
                              <span style="color: #64748b; font-size: 12.5px;">
                                 <?= !empty($blog->created_at) ? date('d M Y, H:i', strtotime($blog->created_at)) : '-'; ?>
                              </span>
                           </td> 
                           <td style="text-align: center; white-space: nowrap;">
                              <?= render_table_action([
                                 'view' => [
                                    'url' => site_url('administrator/blog/view/' . $blog->id),
                                    'permission' => 'blog_view',
                                 ],
                                 'edit' => [
                                    'url' => site_url('administrator/blog/edit/' . $blog->id),
                                    'permission' => 'blog_update',
                                 ],
                                 'delete' => [
                                    'data_href' => site_url('administrator/blog/delete/' . $blog->id),
                                    'permission' => 'blog_delete',
                                 ]
                              ]); ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($blog_counts == 0) :?>
                         <tr>
                           <td colspan="100" style="text-align: center; padding: 35px 20px; color: #94a3b8;">
                              <i class="fa fa-folder-open-o" style="font-size: 32px; display: block; margin-bottom: 8px; color: #cbd5e1;"></i>
                              Belum ada data artikel blog yang tersedia
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'title' ? 'selected' :''; ?> value="title">Title</option>
                           <option <?= $this->input->get('f') == 'slug' ? 'selected' :''; ?> value="slug">Slug</option>
                           <option <?= $this->input->get('f') == 'image' ? 'selected' :''; ?> value="image">Image</option>
                           <option <?= $this->input->get('f') == 'category' ? 'selected' :''; ?> value="category">Category</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' :''; ?> value="status">Status</option>
                           <option <?= $this->input->get('f') == 'author' ? 'selected' :''; ?> value="author">Author</option>
                           <option <?= $this->input->get('f') == 'created_at' ? 'selected' :''; ?> value="created_at">Created At</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/blog');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_blog').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/blog/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>