<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_returns'); ?>      <small><?= cclang('detail', [cclang('tiktok_returns')]); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a href="<?= site_url('administrator/tiktok_returns'); ?>"><?= cclang('tiktok_returns'); ?></a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_returns'); ?></h3>
                     <h5 class="widget-user-desc">Detail <?= cclang('tiktok_returns'); ?></h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_returns" id="form_tiktok_returns" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('tiktok_shop_id') ?> </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->tiktok_shops_shop_name ?: '-'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('return_id') ?> </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->return_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('order_id') ?> </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->order_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('return_type') ?> </label>

                        <div class="col-sm-8">
                           <?php 
                           switch ($tiktok_returns->return_type) {
                              case 'RETURN_AND_REFUND':
                                 echo 'Pengembalian Barang & Dana';
                                 break;
                              case 'REFUND':
                              case 'REFUND_ONLY':
                                 echo 'Pengembalian Dana Saja';
                                 break;
                              default:
                                 echo _ent($tiktok_returns->return_type ?: '-');
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('return_status') ?> </label>

                        <div class="col-sm-8">
                           <?php 
                           switch ($tiktok_returns->return_status) {
                              case 'RETURN_OR_REFUND_REQUEST_PENDING':
                                 echo '<span class="label label-warning">Menunggu Respon Penjual</span>';
                                 break;
                              case 'AWAITING_BUYER_SHIP':
                                 echo '<span class="label label-warning">Menunggu Pembeli Mengirim Barang</span>';
                                 break;
                              case 'BUYER_SHIPPED':
                                 echo '<span class="label label-info">Barang Sedang Dikembalikan</span>';
                                 break;
                              case 'SELLER_RECEIVE_PACKAGE':
                              case 'RETURN_AND_REFUND_PACKAGE_DELIVERED':
                                 echo '<span class="label label-primary">Barang Diterima Penjual</span>';
                                 break;
                              case 'REFUND_PROCESSING':
                              case 'PROCESSING':
                                 echo '<span class="label label-info">Proses Pengembalian Dana</span>';
                                 break;
                              case 'COMPLETE':
                              case 'COMPLETED':
                              case 'REFUND_SUCCESS':
                              case 'SUCCESS':
                                 echo '<span class="label label-success">Selesai</span>';
                                 break;
                              case 'REJECT':
                              case 'REJECTED':
                                 echo '<span class="label label-danger">Ditolak</span>';
                                 break;
                              case 'CANCEL':
                              case 'CANCELLED':
                                 echo '<span class="label label-danger">Dibatalkan</span>';
                                 break;
                              default:
                                 echo '<span class="label label-info">' . _ent($tiktok_returns->return_status ?: '-') . '</span>';
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('return_reason') ?> </label>

                        <div class="col-sm-8">
                           <?php 
                           $r = strtolower(trim($tiktok_returns->return_reason ?? ''));
                           if (strpos($r, 'damaged') !== false || strpos($r, 'rusak') !== false) {
                              echo 'Paket atau produk rusak';
                           } elseif (strpos($r, 'does not match') !== false || strpos($r, 'not_match') !== false || strpos($r, 'tidak sesuai') !== false) {
                              echo 'Produk tidak sesuai deskripsi';
                           } elseif (strpos($r, 'wrong') !== false || strpos($r, 'salah') !== false) {
                              echo 'Salah kirim barang / produk';
                           } elseif (strpos($r, 'missing') !== false || strpos($r, 'kurang') !== false || strpos($r, 'hilang') !== false) {
                              echo 'Komponen atau produk kurang';
                           } elseif (strpos($r, 'defective') !== false || strpos($r, 'cacat') !== false) {
                              echo 'Produk cacat / tidak berfungsi';
                           } elseif (strpos($r, 'counterfeit') !== false || strpos($r, 'palsu') !== false) {
                              echo 'Produk tiruan / tidak original';
                           } elseif (strpos($r, 'not received') !== false || strpos($r, 'not_received') !== false || strpos($r, 'belum terima') !== false) {
                              echo 'Paket pesanan belum diterima';
                           } elseif (strpos($r, 'no longer needed') !== false || strpos($r, 'tidak butuh') !== false) {
                              echo 'Tidak membutuhkannya lagi';
                           } elseif (strpos($r, 'cheaper') !== false || strpos($r, 'murah') !== false) {
                              echo 'Menemukan harga lebih murah';
                           } elseif (strpos($r, 'late') !== false || strpos($r, 'terlambat') !== false) {
                              echo 'Pengiriman barang terlambat';
                           } elseif (strpos($r, 'mutual') !== false || strpos($r, 'sepakat') !== false) {
                              echo 'Kesepakatan pembeli dan penjual';
                           } else {
                              echo _ent($tiktok_returns->return_reason ?: '-');
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('refund_amount') ?> </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_returns->refund_amount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('tracking_number') ?> </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->tracking_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"><?= cclang('return_created_time') ?> </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->return_created_time); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Produk </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr class="bg-gray">
                                        <th style="width: 70px; text-align: center;">Gambar</th>
                                        <th>Nama Produk</th>
                                        <th>Varian / SKU</th>
                                        <th>Nominal Refund</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                                    $items = json_decode($tiktok_returns->items);
                                    if (!empty($items)): 
                                        foreach ($items as $item): 
                                            $img_url = $item->product_image->url ?? "";
                                            $prod_name = $item->product_name ?? "-";
                                            $sku_name = (!empty($item->sku_name) && $item->sku_name != "Default") ? $item->sku_name : "";
                                            $seller_sku = $item->seller_sku ?? "";
                                            $refund = $item->refund_amount->refund_subtotal ?? ($item->refund_amount->refund_total ?? null);
                                    ?>
                                        <tr>
                                            <td style="text-align: center; vertical-align: middle;">
                                                <?php if (!empty($img_url)): ?>
                                                    <a class="fancybox" rel="group" href="<?= $img_url; ?>">
                                                        <img src="<?= $img_url; ?>" style="width: 50px; height: 50px; object-fit: cover; border-radius: 4px;" alt="item">
                                                    </a>
                                                <?php else: ?>
                                                    -
                                                <?php endif; ?>
                                            </td>
                                            <td style="vertical-align: middle;">
                                                <?= _ent($prod_name); ?>
                                            </td>
                                            <td style="vertical-align: middle;">
                                                <?php if (!empty($sku_name)): ?>
                                                    <div><?= _ent($sku_name); ?></div>
                                                <?php endif; ?>
                                                <?php if (!empty($seller_sku)): ?>
                                                    <small class="text-muted">SKU: <?= _ent($seller_sku); ?></small>
                                                <?php endif; ?>
                                                <?php if (empty($sku_name) && empty($seller_sku)): ?>
                                                    -
                                                <?php endif; ?>
                                            </td>
                                            <td style="vertical-align: middle;">
                                                <?= $refund !== null ? "Rp " . number_format($refund, 0, ",", ".") : "-"; ?>
                                            </td>
                                        </tr>
                                    <?php 
                                        endforeach; 
                                    else: 
                                    ?>
                                        <tr>
                                            <td colspan="4" class="text-center text-muted">Tidak ada data produk</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tiktok_returns/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', [cclang('tiktok_returns')]); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
