<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_returns'); ?>      <small><?= cclang('detail', [cclang('tiktok_returns')]); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a href="<?= site_url('administrator/tiktok_returns'); ?>"><?= cclang('tiktok_returns'); ?></a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_returns'); ?></h3>
                     <h5 class="widget-user-desc">Detail <?= cclang('tiktok_returns'); ?></h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_returns" id="form_tiktok_returns" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Toko </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->tiktok_shops_shop_name ?: '-'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Retur </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->return_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Pesanan </label>
                        <div class="col-sm-8" style="padding-top: 7px;">
                           <?php 
                           $order_row = !empty($tiktok_returns->order_id) ? $this->db->get_where('tiktok_orders', ['order_id' => $tiktok_returns->order_id])->row() : null;
                           if ($order_row): ?>
                              <a href="<?= site_url('administrator/tiktok_orders/view/' . $order_row->id); ?>" style="color: #3c8dbc;"><?= _ent($tiktok_returns->order_id); ?></a>
                           <?php else: ?>
                              <span style="color: #3c8dbc;"><?= _ent($tiktok_returns->order_id ?: '-'); ?></span>
                           <?php endif; ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Batas SLA Respon </label>
                        <div class="col-sm-8" style="padding-top: 7px;">
                           <?php
                           if (!empty($tiktok_returns->return_created_time) && in_array($tiktok_returns->return_status, ['RETURN_OR_REFUND_REQUEST_PENDING', 'PROCESSING', 'AWAITING_SELLER_REVIEW'])) {
                              $diff = (strtotime($tiktok_returns->return_created_time) + 172800) - time();
                              if ($diff <= 0) {
                                 echo '<span class="label label-danger">SLA Lewat (Auto-Approve)</span>';
                              } elseif ($diff < 21600) {
                                 $hours = floor($diff / 3600);
                                 $mins = floor(($diff % 3600) / 60);
                                 echo '<span class="label label-danger">' . $hours . 'j ' . $mins . 'm tersisa (Kritis)</span>';
                              } elseif ($diff < 43200) {
                                 $hours = floor($diff / 3600);
                                 $mins = floor(($diff % 3600) / 60);
                                 echo '<span class="label label-warning">' . $hours . 'j ' . $mins . 'm tersisa</span>';
                              } else {
                                 $hours = floor($diff / 3600);
                                 $mins = floor(($diff % 3600) / 60);
                                 echo '<span class="label label-info">' . $hours . 'j ' . $mins . 'm tersisa</span>';
                              }
                           } elseif (in_array($tiktok_returns->return_status, ['AWAITING_BUYER_SHIP', 'BUYER_SHIPPED', 'SELLER_RECEIVE_PACKAGE', 'RETURN_AND_REFUND_PACKAGE_DELIVERED'])) {
                              echo '<span class="label label-primary">Sudah Direspon Penjual</span>';
                           } elseif (in_array($tiktok_returns->return_status, ['COMPLETE', 'COMPLETED', 'REFUND_SUCCESS', 'SUCCESS'])) {
                              echo '<span class="label label-success">Selesai Diproses</span>';
                           } elseif (in_array($tiktok_returns->return_status, ['REJECT', 'REJECTED'])) {
                              echo '<span class="label label-danger">Pengajuan Ditolak</span>';
                           } elseif (in_array($tiktok_returns->return_status, ['CANCEL', 'CANCELLED'])) {
                              echo '<span class="label bg-gray">Dibatalkan Pembeli</span>';
                           } else {
                              echo '<span class="label bg-gray">Tidak Ada SLA Aktif</span>';
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tipe Retur </label>

                        <div class="col-sm-8">
                           <?php 
                           switch ($tiktok_returns->return_type) {
                              case 'RETURN_AND_REFUND':
                                 echo 'Pengembalian Barang & Dana';
                                 break;
                              case 'REFUND':
                              case 'REFUND_ONLY':
                                 echo 'Pengembalian Dana Saja';
                                 break;
                              default:
                                 echo _ent($tiktok_returns->return_type ?: '-');
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Retur </label>

                        <div class="col-sm-8">
                           <?php 
                           switch ($tiktok_returns->return_status) {
                              case 'RETURN_OR_REFUND_REQUEST_PENDING':
                                 echo '<span class="label label-warning">Menunggu Respon Penjual</span>';
                                 break;
                              case 'AWAITING_BUYER_SHIP':
                                 echo '<span class="label label-warning">Menunggu Pembeli Mengirim Barang</span>';
                                 break;
                              case 'BUYER_SHIPPED':
                                 echo '<span class="label label-info">Barang Sedang Dikembalikan</span>';
                                 break;
                              case 'SELLER_RECEIVE_PACKAGE':
                              case 'RETURN_AND_REFUND_PACKAGE_DELIVERED':
                                 echo '<span class="label label-primary">Barang Diterima Penjual</span>';
                                 break;
                              case 'REFUND_PROCESSING':
                              case 'PROCESSING':
                                 echo '<span class="label label-info">Proses Pengembalian Dana</span>';
                                 break;
                              case 'COMPLETE':
                              case 'COMPLETED':
                              case 'REFUND_SUCCESS':
                              case 'SUCCESS':
                                 echo '<span class="label label-success">Selesai</span>';
                                 break;
                              case 'REJECT':
                              case 'REJECTED':
                                 echo '<span class="label label-danger">Ditolak</span>';
                                 break;
                              case 'CANCEL':
                              case 'CANCELLED':
                                 echo '<span class="label label-danger">Dibatalkan</span>';
                                 break;
                              default:
                                 echo '<span class="label label-info">' . _ent($tiktok_returns->return_status ?: '-') . '</span>';
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alasan Retur </label>

                        <div class="col-sm-8">
                           <?php 
                           $r = strtolower(trim($tiktok_returns->return_reason ?? ''));
                           if (strpos($r, 'damaged') !== false || strpos($r, 'rusak') !== false) {
                              echo 'Paket atau produk rusak';
                           } elseif (strpos($r, 'does not match') !== false || strpos($r, 'not_match') !== false || strpos($r, 'tidak sesuai') !== false) {
                              echo 'Produk tidak sesuai deskripsi';
                           } elseif (strpos($r, 'wrong') !== false || strpos($r, 'salah') !== false) {
                              echo 'Salah kirim barang / produk';
                           } elseif (strpos($r, 'missing') !== false || strpos($r, 'kurang') !== false || strpos($r, 'hilang') !== false) {
                              echo 'Komponen atau produk kurang';
                           } elseif (strpos($r, 'defective') !== false || strpos($r, 'cacat') !== false) {
                              echo 'Produk cacat / tidak berfungsi';
                           } elseif (strpos($r, 'counterfeit') !== false || strpos($r, 'palsu') !== false) {
                              echo 'Produk tiruan / tidak original';
                           } elseif (strpos($r, 'not received') !== false || strpos($r, 'not_received') !== false || strpos($r, 'belum terima') !== false) {
                              echo 'Paket pesanan belum diterima';
                           } elseif (strpos($r, 'no longer needed') !== false || strpos($r, 'tidak butuh') !== false) {
                              echo 'Tidak membutuhkannya lagi';
                           } elseif (strpos($r, 'cheaper') !== false || strpos($r, 'murah') !== false) {
                              echo 'Menemukan harga lebih murah';
                           } elseif (strpos($r, 'late') !== false || strpos($r, 'terlambat') !== false) {
                              echo 'Pengiriman barang terlambat';
                           } elseif (strpos($r, 'mutual') !== false || strpos($r, 'sepakat') !== false) {
                              echo 'Kesepakatan pembeli dan penjual';
                           } else {
                              echo _ent($tiktok_returns->return_reason ?: '-');
                           }
                           ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nominal Pengembalian Dana </label>

                        <div class="col-sm-8">
                           Rp <?= number_format($tiktok_returns->refund_amount, 0, ',', '.'); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nomor Resi </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->tracking_number); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Waktu Pengajuan </label>

                        <div class="col-sm-8">
                           <?= _ent($tiktok_returns->return_created_time); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Produk </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr class="bg-gray">
                                        <th style="width: 70px; text-align: center;">Gambar</th>
                                        <th>Nama Produk</th>
                                        <th>Varian / SKU</th>
                                        <th>Nominal Refund</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                                    $items = json_decode($tiktok_returns->items);
                                    if (!empty($items)): 
                                        foreach ($items as $item): 
                                            $img_url = $item->product_image->url ?? "";
                                            $prod_name = $item->product_name ?? "-";
                                            $sku_name = (!empty($item->sku_name) && $item->sku_name != "Default") ? $item->sku_name : "";
                                            $seller_sku = $item->seller_sku ?? "";
                                            $refund = $item->refund_amount->refund_subtotal ?? ($item->refund_amount->refund_total ?? null);
                                    ?>
                                        <tr>
                                            <td style="text-align: center; vertical-align: middle;">
                                                <?php if (!empty($img_url)): ?>
                                                    <a class="fancybox" rel="group" href="<?= $img_url; ?>">
                                                        <img src="<?= $img_url; ?>" style="width: 50px; height: 50px; object-fit: cover; border-radius: 4px;" alt="item">
                                                    </a>
                                                <?php else: ?>
                                                    -
                                                <?php endif; ?>
                                            </td>
                                            <td style="vertical-align: middle;">
                                                 <div><?= _ent($prod_name); ?></div>
                                                 <?php if (!empty($seller_sku)): ?>
                                                     <small class="text-muted">(SKU: <?= _ent($seller_sku); ?>)</small>
                                                 <?php endif; ?>
                                             </td>
                                            <td style="vertical-align: middle;">
                                                <?php if (!empty($sku_name)): ?>
                                                    <div><?= _ent($sku_name); ?></div>
                                                <?php endif; ?>
                                                <?php if (!empty($seller_sku)): ?>
                                                    <small class="text-muted">SKU: <?= _ent($seller_sku); ?></small>
                                                <?php endif; ?>
                                                <?php if (empty($sku_name) && empty($seller_sku)): ?>
                                                    -
                                                <?php endif; ?>
                                            </td>
                                            <td style="vertical-align: middle;">
                                                <?= $refund !== null ? "Rp " . number_format($refund, 0, ",", ".") : "-"; ?>
                                            </td>
                                        </tr>
                                    <?php 
                                        endforeach; 
                                    else: 
                                    ?>
                                        <tr>
                                            <td colspan="4" class="text-center text-muted">Tidak ada data produk</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php if ($tiktok_returns->return_status == 'RETURN_OR_REFUND_REQUEST_PENDING'): ?>
                            <a class="btn btn-flat btn-success btn_action btn-approve-return" href="<?= site_url('administrator/tiktok_returns/approve/' . $tiktok_returns->id); ?>" data-return-id="<?= $tiktok_returns->return_id; ?>" title="Setujui Pengajuan Retur"><i class="fa fa-check"></i> Setujui Retur</a>
                            <button type="button" class="btn btn-flat btn-danger btn_action" data-toggle="modal" data-target="#modal-reject-return"><i class="fa fa-times"></i> Tolak Retur</button>
                        <?php endif; ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="Kembali ke Daftar (Ctrl+x)" href="<?= site_url('administrator/tiktok_returns/'); ?>"><i class="fa fa-undo"></i> Kembali ke Daftar</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>

   <!-- Modal Tolak Pengajuan Retur -->
   <div class="modal fade" id="modal-reject-return" tabindex="-1" role="dialog" aria-labelledby="modalRejectLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <form id="form-reject-return" method="POST" action="<?= site_url('administrator/tiktok_returns/reject/' . $tiktok_returns->id); ?>">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="modalRejectLabel">Tolak Pengajuan Retur</h4>
           </div>
           <div class="modal-body">
             <p class="text-muted">Pilih alasan resmi penolakan untuk pengajuan retur <span style="color: #3c8dbc;">ID: <?= _ent($tiktok_returns->return_id); ?></span> sesuai ketentuan TikTok Shop:</p>
             <div class="form-group">
               <label>Alasan Penolakan Resmi <span class="text-danger">*</span></label>
               <select name="reject_reason" id="select-reject-reason" class="form-control" required>
                 <option value="">-- Pilih Alasan Penolakan --</option>
                 <?php if (!empty($reject_reasons)): ?>
                   <?php foreach ($reject_reasons as $reason): ?>
                     <option value="<?= _ent($reason->reason_code); ?>"><?= _ent($reason->reason_text); ?></option>
                   <?php endforeach; ?>
                 <?php else: ?>
                   <option value="seller_reject_reason_buyer_reason_not_valid">Alasan pembeli tidak valid atau tidak sesuai kondisi sebenarnya</option>
                   <option value="seller_reject_reason_package_delivered_in_good_condition">Paket dan produk telah terkirim dalam kondisi baik dan lengkap</option>
                   <option value="seller_reject_reason_insufficient_evidence">Bukti foto atau video unboxing yang dilampirkan pembeli tidak memadai</option>
                   <option value="seller_reject_reason_mutual_agreement">Telah tercapai kesepakatan solusi alternatif bersama pembeli</option>
                 <?php endif; ?>
               </select>
             </div>
             <div class="form-group">
               <label>Catatan / Keterangan untuk Pembeli (Opsional)</label>
               <textarea name="comments" class="form-control" rows="3" placeholder="Tuliskan penjelasan tambahan jika diperlukan..."></textarea>
             </div>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Batal</button>
             <button type="submit" class="btn btn-danger btn-flat"><i class="fa fa-times"></i> Konfirmasi Tolak Retur</button>
           </div>
         </form>
       </div>
     </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).ready(function(){
  $('.btn-approve-return').click(function(e){
    e.preventDefault();
    var url = $(this).attr('href');
    var returnId = $(this).data('return-id');
    swal({
        title: "Setujui Retur?",
        text: "Anda akan menyetujui pengajuan pengembalian (ID: " + returnId + "). Pembeli akan diinstruksikan untuk mengirimkan barang ke alamat toko Anda.",
        type: "info",
        showCancelButton: true,
        confirmButtonColor: "#00a65a",
        confirmButtonText: "Ya, Setujui",
        cancelButtonText: "Batal",
        closeOnConfirm: true
      },
      function(isConfirm){
        if (isConfirm) {
          document.location.href = url;            
        }
      });
    return false;
  });
});
</script>
