
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tiktok_finance/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_finance') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tiktok_finance') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <a class="btn btn-flat btn-success" id="btn_sync" title="Tarik Data Keuangan dari TikTok Shop" href="<?= site_url('administrator/tiktok_finance/sync'); ?>"><i class="fa fa-refresh"></i> Tarik Data Keuangan</a>
                        <?php is_allowed('tiktok_finance_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('tiktok_finance') ?>']); ?>" href="<?= site_url('administrator/tiktok_finance/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_finance_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('tiktok_finance') ?>']); ?>" href="<?= site_url('administrator/tiktok_finance/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_finance') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tiktok_finance')]); ?>  <i class="label bg-yellow"><?= $tiktok_finance_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tiktok_finance" id="form_tiktok_finance" action="<?= base_url('administrator/tiktok_finance/index'); ?>">
                  

                  <div class="table-responsive" style="overflow-x: auto; width: 100%;"> 
                  <table class="table table-bordered table-striped dataTable" style="min-width: 1200px; width: 100%;">
                     <thead>
                        <tr style="white-space: nowrap;">
                           <th width="20">
                              <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="Pilih Semua">
                           </th>
                           <th>Nama Toko</th>
                           <th>ID Statement</th>
                           <th>Tanggal Statement</th>
                           <th>ID Pencairan</th>
                           <th>Status Pencairan</th>
                           <th>Total Pencairan</th>
                           <th>Omzet Kotor</th>
                           <th>Biaya Pengiriman</th>
                           <th>Biaya Layanan</th>
                           <th style="width: 260px; min-width: 260px; text-align: center;">Aksi</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_tiktok_finance">
                     <?php foreach($tiktok_finances as $tiktok_finance): ?>
                        <tr style="white-space: nowrap;">
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tiktok_finance->id; ?>">
                           </td>
                           <td>
                              <?php if ($tiktok_finance->tiktok_shop_id): ?>
                                 <?= anchor('administrator/tiktok_shops/view/'.$tiktok_finance->tiktok_shop_id.'?popup=show', $tiktok_finance->tiktok_shops_shop_name, ['class' => 'popup-view']); ?>
                              <?php else: ?>
                                 -
                              <?php endif; ?>
                           </td>
                           <td><?= _ent($tiktok_finance->statement_id); ?></td>
                           <td><?= $tiktok_finance->statement_time ? date('d/m/Y H:i', strtotime($tiktok_finance->statement_time)) : '-'; ?></td>
                           <td><?= _ent($tiktok_finance->payout_id ?: '-'); ?></td>
                           <td>
                              <?php 
                              $status = strtoupper($tiktok_finance->payment_status);
                              if ($status == 'PAID' || $status == 'COMPLETED' || $status == 'SUCCESS') {
                                 echo '<span class="label label-success">' . $status . '</span>';
                              } elseif ($status == 'FAILED' || $status == 'CANCELLED') {
                                 echo '<span class="label label-danger">' . $status . '</span>';
                              } else {
                                 echo '<span class="label label-warning">' . $status . '</span>';
                              }
                              ?>
                           </td>
                           <td>Rp <?= number_format($tiktok_finance->settlement_amount, 0, ',', '.'); ?></td>
                           <td>Rp <?= number_format($tiktok_finance->revenue_amount, 0, ',', '.'); ?></td>
                           <td>Rp <?= number_format($tiktok_finance->shipping_fee_amount, 0, ',', '.'); ?></td>
                           <td>Rp <?= number_format($tiktok_finance->fee_amount, 0, ',', '.'); ?></td>
                           <td style="text-align: left !important;">
                              <?php is_allowed('tiktok_finance_view', function() use ($tiktok_finance){?>
                                 <a href="<?= site_url('administrator/tiktok_finance/single_pdf/' .$tiktok_finance->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> PDF</a>
                                 <a href="<?= site_url('administrator/tiktok_finance/view/' . $tiktok_finance->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> Lihat</a>
                              <?php }) ?>
                              <?php is_allowed('tiktok_finance_delete', function() use ($tiktok_finance){?>
                                 <a href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_finance/delete/' . $tiktok_finance->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Hapus</a>
                              <?php }) ?>
                           </td>
                        </tr>
                     <?php endforeach; ?>
                      <?php if ($tiktok_finance_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Keuangan TikTok data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                            <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'statement_id' ? 'selected' :''; ?> value="statement_id">ID Statement</option>
                            <option <?= $this->input->get('f') == 'tiktok_shop_id' ? 'selected' :''; ?> value="tiktok_shop_id">Nama Toko</option>
                            <option <?= $this->input->get('f') == 'statement_time' ? 'selected' :''; ?> value="statement_time">Tanggal Statement</option>
                            <option <?= $this->input->get('f') == 'payout_id' ? 'selected' :''; ?> value="payout_id">ID Pencairan</option>
                            <option <?= $this->input->get('f') == 'payment_status' ? 'selected' :''; ?> value="payment_status">Status Pencairan</option>
                            <option <?= $this->input->get('f') == 'settlement_amount' ? 'selected' :''; ?> value="settlement_amount">Total Pencairan</option>
                            <option <?= $this->input->get('f') == 'revenue_amount' ? 'selected' :''; ?> value="revenue_amount">Omzet Kotor</option>
                            <option <?= $this->input->get('f') == 'shipping_fee_amount' ? 'selected' :''; ?> value="shipping_fee_amount">Biaya Pengiriman</option>
                            <option <?= $this->input->get('f') == 'fee_amount' ? 'selected' :''; ?> value="fee_amount">Biaya Layanan</option>
                           </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tiktok_finance');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tiktok_finance').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tiktok_finance/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>