
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Daftar Gudang      <small><?= cclang('detail', ['Daftar Gudang']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tiktok_warehouses'); ?>">Daftar Gudang</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Daftar Gudang</h3>
                     <h5 class="widget-user-desc">Detail Daftar Gudang</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tiktok_warehouses" id="form_tiktok_warehouses" >
                    
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_warehouses->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Gudang </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_warehouses->name); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Gudang TikTok </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_warehouses->tiktok_warehouse_id); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tipe Gudang </label>
                        <div class="col-sm-8">
                           <?php 
                              if ($tiktok_warehouses->warehouse_type == "SALES_WAREHOUSE") {
                                 echo "Gudang Penjualan";
                              } elseif ($tiktok_warehouses->warehouse_type == "RETURN_WAREHOUSE") {
                                 echo "Gudang Retur";
                              } else {
                                 echo _ent($tiktok_warehouses->warehouse_type);
                              }
                           ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat Gudang </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_warehouses->address ?: "-"); ?>
                        </div>
                    </div>



                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Gudang Utama </label>
                        <div class="col-sm-8">
                           <?= $tiktok_warehouses->is_default ? "Ya" : "Tidak"; ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>
                        <div class="col-sm-8">
                           <?= in_array(strtoupper($tiktok_warehouses->effect_status), ["ENABLED", "EFFECTIVE"]) ? '<span class="label label-success">Aktif</span>' : '<span class="label label-danger">Non-Aktif</span>'; ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Toko </label>
                        <div class="col-sm-8">
                           <?= _ent($tiktok_warehouses->shop_id); ?>
                        </div>
                    </div>
                                                            <div class="form-group">
                        <label class="col-sm-2 control-label">Opsi Pengiriman </label>
                        <div class="col-sm-8">
                            <table class="table table-bordered table-striped" style="margin-top: 5px;">
                                <thead>
                                    <tr class="bg-gray">
                                        <th>Opsi Pengiriman</th>
                                        <th>Cakupan</th>
                                        <th>Kurir Logistik</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($tiktok_warehouses->delivery_options)): ?>
                                        <?php foreach ($tiktok_warehouses->delivery_options as $dopt): ?>
                                            <tr>
                                                <td>
                                                    <strong><?= _ent($dopt->name); ?></strong><br>
                                                    <small class="text-muted">ID: <?= _ent($dopt->tiktok_delivery_option_id); ?></small>
                                                </td>
                                                <td><?= _ent($dopt->scope ?: "-"); ?></td>
                                                <td>
                                                    <?php if (!empty($dopt->shipping_providers)): ?>
                                                        <ul style="padding-left: 20px; margin-bottom: 0;">
                                                            <?php foreach ($dopt->shipping_providers as $sp): ?>
                                                                <li><?= _ent($sp->name); ?> <small class="text-muted">(ID: <?= _ent($sp->tiktok_provider_id); ?>)</small></li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    <?php else: ?>
                                                        <em class="text-muted">Tidak ada kurir terdaftar</em>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <tr>
                                            <td colspan="3" class="text-center text-muted">Belum ada data opsi pengiriman. Klik "Tarik Data Gudang" untuk memperbarui.</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <br>

                    <div class="view-nav">
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="Kembali ke Daftar Gudang" href="<?= site_url('administrator/tiktok_warehouses/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Gudang']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
