
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tiktok_warehouses/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tiktok_warehouses') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tiktok_warehouses') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tiktok_warehouses_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('tiktok_warehouses')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tiktok_warehouses/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('tiktok_warehouses')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_warehouses_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('tiktok_warehouses') ?>']); ?>" href="<?= site_url('administrator/tiktok_warehouses/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tiktok_warehouses_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('tiktok_warehouses') ?>']); ?>" href="<?= site_url('administrator/tiktok_warehouses/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tiktok_warehouses') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tiktok_warehouses')]); ?>  <i class="label bg-yellow"><?= $tiktok_warehouses_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tiktok_warehouses" id="form_tiktok_warehouses" action="<?= base_url('administrator/tiktok_warehouses/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('shop_id') ?></th>
                           <th> <?= cclang('tiktok_warehouse_id') ?></th>
                           <th> <?= cclang('branch_mapping_id') ?></th>
                           <th> <?= cclang('name') ?></th>
                           <th> <?= cclang('address') ?></th>
                           <th> <?= cclang('warehouse_type') ?></th>
                           <th> <?= cclang('effect_status') ?></th>
                           <th> <?= cclang('is_default') ?></th>
                           <th> <?= cclang('created_at') ?></th>
                           <th> <?= cclang('updated_at') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_tiktok_warehouses">
                     <?php foreach($tiktok_warehousess as $tiktok_warehouses): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tiktok_warehouses->id; ?>">
                           </td>
                                                       
                           <td><?= _ent($tiktok_warehouses->shop_id); ?></td> 
                           <td><?= _ent($tiktok_warehouses->tiktok_warehouse_id); ?></td> 
                           <td><?= _ent($tiktok_warehouses->branch_mapping_id); ?></td> 
                           <td><?= _ent($tiktok_warehouses->name); ?></td> 
                           <td><?= _ent($tiktok_warehouses->address); ?></td> 
                           <td><?= _ent($tiktok_warehouses->warehouse_type); ?></td> 
                           <td><?= _ent($tiktok_warehouses->effect_status); ?></td> 
                           <td><?= _ent($tiktok_warehouses->is_default); ?></td> 
                           <td><?= _ent($tiktok_warehouses->created_at); ?></td> 
                           <td><?= _ent($tiktok_warehouses->updated_at); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('tiktok_warehouses_view', function() use ($tiktok_warehouses){?>
                                 <a href="<?= site_url('administrator/tiktok_warehouses/single_pdf/' .$tiktok_warehouses->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/tiktok_warehouses/view/' . $tiktok_warehouses->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('tiktok_warehouses_update', function() use ($tiktok_warehouses){?>
                              <a href="<?= site_url('administrator/tiktok_warehouses/edit/' . $tiktok_warehouses->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('tiktok_warehouses_delete', function() use ($tiktok_warehouses){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/tiktok_warehouses/delete/' . $tiktok_warehouses->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tiktok_warehouses_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Gudang TikTok data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'shop_id' ? 'selected' :''; ?> value="shop_id">Shop Id</option>
                           <option <?= $this->input->get('f') == 'tiktok_warehouse_id' ? 'selected' :''; ?> value="tiktok_warehouse_id">Tiktok Warehouse Id</option>
                           <option <?= $this->input->get('f') == 'branch_mapping_id' ? 'selected' :''; ?> value="branch_mapping_id">Branch Mapping Id</option>
                           <option <?= $this->input->get('f') == 'name' ? 'selected' :''; ?> value="name">Name</option>
                           <option <?= $this->input->get('f') == 'address' ? 'selected' :''; ?> value="address">Address</option>
                           <option <?= $this->input->get('f') == 'warehouse_type' ? 'selected' :''; ?> value="warehouse_type">Warehouse Type</option>
                           <option <?= $this->input->get('f') == 'effect_status' ? 'selected' :''; ?> value="effect_status">Effect Status</option>
                           <option <?= $this->input->get('f') == 'is_default' ? 'selected' :''; ?> value="is_default">Is Default</option>
                           <option <?= $this->input->get('f') == 'created_at' ? 'selected' :''; ?> value="created_at">Created At</option>
                           <option <?= $this->input->get('f') == 'updated_at' ? 'selected' :''; ?> value="updated_at">Updated At</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tiktok_warehouses');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tiktok_warehouses').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tiktok_warehouses/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>